#ifndef WASMOON_FIBER_PROTOCOL_H
#define WASMOON_FIBER_PROTOCOL_H

typedef enum {
    WASMOON_FIBER_STATE_INVALID = -1,
    WASMOON_FIBER_STATE_READY = 0,
    WASMOON_FIBER_STATE_RUNNING = 1,
    WASMOON_FIBER_STATE_SUSPENDED = 2,
    WASMOON_FIBER_STATE_RETURNED = 3,
    WASMOON_FIBER_STATE_CANCELLED = 4,
} wasmoon_fiber_state_code_t;

typedef enum {
    WASMOON_FIBER_ADVANCE_INVALID_HANDLE = -1,
    WASMOON_FIBER_ADVANCE_WRONG_THREAD = -2,
    WASMOON_FIBER_ADVANCE_INVALID_TRANSITION = -3,
    WASMOON_FIBER_ADVANCE_INVALID_STATE = -4,
    WASMOON_FIBER_ADVANCE_SUSPENDED = 0,
    WASMOON_FIBER_ADVANCE_RETURNED = 1,
} wasmoon_fiber_advance_code_t;

typedef enum {
    WASMOON_FIBER_CANCEL_INVALID_HANDLE = -1,
    WASMOON_FIBER_CANCEL_WRONG_THREAD = -2,
    WASMOON_FIBER_CANCEL_INVALID_TRANSITION = -3,
    WASMOON_FIBER_CANCEL_OK = 0,
} wasmoon_fiber_cancel_code_t;

#endif
