; Generated by scripts/msvc/generate_guest_bridges.py. Do not edit.
option casemap:none
.code
EXTERN atomic_notify_indexed_msvc_target:QWORD
PUBLIC atomic_notify_indexed_msvc_guest
atomic_notify_indexed_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [atomic_notify_indexed_msvc_target]
    add rsp, 40
    ret
atomic_notify_indexed_msvc_guest ENDP
EXTERN atomic_wait32_indexed_msvc_target:QWORD
PUBLIC atomic_wait32_indexed_msvc_guest
atomic_wait32_indexed_msvc_guest PROC
    sub rsp, 40
    mov QWORD PTR [rsp+32], r8
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [atomic_wait32_indexed_msvc_target]
    add rsp, 40
    ret
atomic_wait32_indexed_msvc_guest ENDP
EXTERN atomic_wait64_indexed_msvc_target:QWORD
PUBLIC atomic_wait64_indexed_msvc_guest
atomic_wait64_indexed_msvc_guest PROC
    sub rsp, 40
    mov QWORD PTR [rsp+32], r8
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [atomic_wait64_indexed_msvc_target]
    add rsp, 40
    ret
atomic_wait64_indexed_msvc_guest ENDP
EXTERN continuation_bind_msvc_target:QWORD
PUBLIC continuation_bind_msvc_guest
continuation_bind_msvc_guest PROC
    sub rsp, 40
    mov QWORD PTR [rsp+32], r8
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [continuation_bind_msvc_target]
    add rsp, 40
    ret
continuation_bind_msvc_guest ENDP
EXTERN continuation_new_msvc_target:QWORD
PUBLIC continuation_new_msvc_guest
continuation_new_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [continuation_new_msvc_target]
    add rsp, 40
    ret
continuation_new_msvc_guest ENDP
EXTERN continuation_resume_msvc_target:QWORD
PUBLIC continuation_resume_msvc_guest
continuation_resume_msvc_guest PROC
    sub rsp, 72
    mov QWORD PTR [rsp+32], r8
    mov QWORD PTR [rsp+40], r9
    mov rax, QWORD PTR [rsp+80]
    mov QWORD PTR [rsp+48], rax
    mov rax, QWORD PTR [rsp+88]
    mov QWORD PTR [rsp+56], rax
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [continuation_resume_msvc_target]
    add rsp, 72
    ret
continuation_resume_msvc_guest ENDP
EXTERN continuation_suspend_msvc_target:QWORD
PUBLIC continuation_suspend_msvc_guest
continuation_suspend_msvc_guest PROC
    sub rsp, 56
    mov QWORD PTR [rsp+32], r8
    mov QWORD PTR [rsp+40], r9
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [continuation_suspend_msvc_target]
    add rsp, 56
    ret
continuation_suspend_msvc_guest ENDP
EXTERN continuation_switch_msvc_target:QWORD
PUBLIC continuation_switch_msvc_guest
continuation_switch_msvc_guest PROC
    sub rsp, 56
    mov QWORD PTR [rsp+32], r8
    mov QWORD PTR [rsp+40], r9
    mov rax, QWORD PTR [rsp+64]
    mov QWORD PTR [rsp+48], rax
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [continuation_switch_msvc_target]
    add rsp, 56
    ret
continuation_switch_msvc_guest ENDP
EXTERN data_drop_impl_msvc_target:QWORD
PUBLIC data_drop_impl_msvc_guest
data_drop_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [data_drop_impl_msvc_target]
    add rsp, 40
    ret
data_drop_impl_msvc_guest ENDP
EXTERN elem_drop_impl_msvc_target:QWORD
PUBLIC elem_drop_impl_msvc_guest
elem_drop_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [elem_drop_impl_msvc_target]
    add rsp, 40
    ret
elem_drop_impl_msvc_guest ENDP
EXTERN exception_get_ref_impl_msvc_target:QWORD
PUBLIC exception_get_ref_impl_msvc_guest
exception_get_ref_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [exception_get_ref_impl_msvc_target]
    add rsp, 40
    ret
exception_get_ref_impl_msvc_guest ENDP
EXTERN gc_alloc_array_from_slots_slow_impl_msvc_target:QWORD
PUBLIC gc_alloc_array_from_slots_slow_impl_msvc_guest
gc_alloc_array_from_slots_slow_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_alloc_array_from_slots_slow_impl_msvc_target]
    add rsp, 40
    ret
gc_alloc_array_from_slots_slow_impl_msvc_guest ENDP
EXTERN gc_alloc_array_from_values_slow_msvc_target:QWORD
PUBLIC gc_alloc_array_from_values_slow_msvc_guest
gc_alloc_array_from_values_slow_msvc_guest PROC
    sub rsp, 56
    mov QWORD PTR [rsp+32], r8
    mov QWORD PTR [rsp+40], r9
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_alloc_array_from_values_slow_msvc_target]
    add rsp, 56
    ret
gc_alloc_array_from_values_slow_msvc_guest ENDP
EXTERN gc_alloc_array_slow_msvc_target:QWORD
PUBLIC gc_alloc_array_slow_msvc_guest
gc_alloc_array_slow_msvc_guest PROC
    sub rsp, 56
    mov QWORD PTR [rsp+32], r8
    mov QWORD PTR [rsp+40], r9
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_alloc_array_slow_msvc_target]
    add rsp, 56
    ret
gc_alloc_array_slow_msvc_guest ENDP
EXTERN gc_alloc_array_wide_slow_impl_msvc_target:QWORD
PUBLIC gc_alloc_array_wide_slow_impl_msvc_guest
gc_alloc_array_wide_slow_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_alloc_array_wide_slow_impl_msvc_target]
    add rsp, 40
    ret
gc_alloc_array_wide_slow_impl_msvc_guest ENDP
EXTERN gc_alloc_struct_slow_msvc_target:QWORD
PUBLIC gc_alloc_struct_slow_msvc_guest
gc_alloc_struct_slow_msvc_guest PROC
    sub rsp, 56
    mov QWORD PTR [rsp+32], r8
    mov QWORD PTR [rsp+40], r9
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_alloc_struct_slow_msvc_target]
    add rsp, 56
    ret
gc_alloc_struct_slow_msvc_guest ENDP
EXTERN gc_alloc_struct_wide_slow_impl_msvc_target:QWORD
PUBLIC gc_alloc_struct_wide_slow_impl_msvc_guest
gc_alloc_struct_wide_slow_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_alloc_struct_wide_slow_impl_msvc_target]
    add rsp, 40
    ret
gc_alloc_struct_wide_slow_impl_msvc_guest ENDP
EXTERN gc_array_copy_impl_msvc_target:QWORD
PUBLIC gc_array_copy_impl_msvc_guest
gc_array_copy_impl_msvc_guest PROC
    sub rsp, 40
    mov QWORD PTR [rsp+32], r8
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_array_copy_impl_msvc_target]
    add rsp, 40
    ret
gc_array_copy_impl_msvc_guest ENDP
EXTERN gc_array_fill_impl_msvc_target:QWORD
PUBLIC gc_array_fill_impl_msvc_guest
gc_array_fill_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_array_fill_impl_msvc_target]
    add rsp, 40
    ret
gc_array_fill_impl_msvc_guest ENDP
EXTERN gc_array_fill_v128_impl_msvc_target:QWORD
PUBLIC gc_array_fill_v128_impl_msvc_guest
gc_array_fill_v128_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_array_fill_v128_impl_msvc_target]
    add rsp, 40
    ret
gc_array_fill_v128_impl_msvc_guest ENDP
EXTERN gc_array_get_impl_msvc_target:QWORD
PUBLIC gc_array_get_impl_msvc_guest
gc_array_get_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_array_get_impl_msvc_target]
    add rsp, 40
    ret
gc_array_get_impl_msvc_guest ENDP
EXTERN gc_array_get_v128_impl_msvc_target:QWORD
PUBLIC gc_array_get_v128_impl_msvc_guest
gc_array_get_v128_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_array_get_v128_impl_msvc_target]
    add rsp, 40
    ret
gc_array_get_v128_impl_msvc_guest ENDP
EXTERN gc_array_init_data_impl_msvc_target:QWORD
PUBLIC gc_array_init_data_impl_msvc_guest
gc_array_init_data_impl_msvc_guest PROC
    sub rsp, 56
    mov QWORD PTR [rsp+32], r8
    mov QWORD PTR [rsp+40], r9
    mov rax, QWORD PTR [rsp+64]
    mov QWORD PTR [rsp+48], rax
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_array_init_data_impl_msvc_target]
    add rsp, 56
    ret
gc_array_init_data_impl_msvc_guest ENDP
EXTERN gc_array_init_elem_impl_msvc_target:QWORD
PUBLIC gc_array_init_elem_impl_msvc_guest
gc_array_init_elem_impl_msvc_guest PROC
    sub rsp, 56
    mov QWORD PTR [rsp+32], r8
    mov QWORD PTR [rsp+40], r9
    mov rax, QWORD PTR [rsp+64]
    mov QWORD PTR [rsp+48], rax
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_array_init_elem_impl_msvc_target]
    add rsp, 56
    ret
gc_array_init_elem_impl_msvc_guest ENDP
EXTERN gc_array_len_impl_msvc_target:QWORD
PUBLIC gc_array_len_impl_msvc_guest
gc_array_len_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_array_len_impl_msvc_target]
    add rsp, 40
    ret
gc_array_len_impl_msvc_guest ENDP
EXTERN gc_array_new_data_impl_msvc_target:QWORD
PUBLIC gc_array_new_data_impl_msvc_guest
gc_array_new_data_impl_msvc_guest PROC
    sub rsp, 40
    mov QWORD PTR [rsp+32], r8
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_array_new_data_impl_msvc_target]
    add rsp, 40
    ret
gc_array_new_data_impl_msvc_guest ENDP
EXTERN gc_array_new_elem_impl_msvc_target:QWORD
PUBLIC gc_array_new_elem_impl_msvc_guest
gc_array_new_elem_impl_msvc_guest PROC
    sub rsp, 40
    mov QWORD PTR [rsp+32], r8
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_array_new_elem_impl_msvc_target]
    add rsp, 40
    ret
gc_array_new_elem_impl_msvc_guest ENDP
EXTERN gc_array_new_impl_msvc_target:QWORD
PUBLIC gc_array_new_impl_msvc_guest
gc_array_new_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_array_new_impl_msvc_target]
    add rsp, 40
    ret
gc_array_new_impl_msvc_guest ENDP
EXTERN gc_array_set_impl_msvc_target:QWORD
PUBLIC gc_array_set_impl_msvc_guest
gc_array_set_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_array_set_impl_msvc_target]
    add rsp, 40
    ret
gc_array_set_impl_msvc_guest ENDP
EXTERN gc_array_set_v128_impl_msvc_target:QWORD
PUBLIC gc_array_set_v128_impl_msvc_guest
gc_array_set_v128_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_array_set_v128_impl_msvc_target]
    add rsp, 40
    ret
gc_array_set_v128_impl_msvc_guest ENDP
EXTERN gc_ref_cast_impl_msvc_target:QWORD
PUBLIC gc_ref_cast_impl_msvc_guest
gc_ref_cast_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_ref_cast_impl_msvc_target]
    add rsp, 40
    ret
gc_ref_cast_impl_msvc_guest ENDP
EXTERN gc_ref_test_impl_msvc_target:QWORD
PUBLIC gc_ref_test_impl_msvc_guest
gc_ref_test_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_ref_test_impl_msvc_target]
    add rsp, 40
    ret
gc_ref_test_impl_msvc_guest ENDP
EXTERN gc_register_array_inline_msvc_target:QWORD
PUBLIC gc_register_array_inline_msvc_guest
gc_register_array_inline_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_register_array_inline_msvc_target]
    add rsp, 40
    ret
gc_register_array_inline_msvc_guest ENDP
EXTERN gc_register_struct_inline_msvc_target:QWORD
PUBLIC gc_register_struct_inline_msvc_guest
gc_register_struct_inline_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_register_struct_inline_msvc_target]
    add rsp, 40
    ret
gc_register_struct_inline_msvc_guest ENDP
EXTERN gc_struct_get_impl_msvc_target:QWORD
PUBLIC gc_struct_get_impl_msvc_guest
gc_struct_get_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_struct_get_impl_msvc_target]
    add rsp, 40
    ret
gc_struct_get_impl_msvc_guest ENDP
EXTERN gc_struct_get_v128_impl_msvc_target:QWORD
PUBLIC gc_struct_get_v128_impl_msvc_guest
gc_struct_get_v128_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_struct_get_v128_impl_msvc_target]
    add rsp, 40
    ret
gc_struct_get_v128_impl_msvc_guest ENDP
EXTERN gc_struct_new_impl_msvc_target:QWORD
PUBLIC gc_struct_new_impl_msvc_guest
gc_struct_new_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_struct_new_impl_msvc_target]
    add rsp, 40
    ret
gc_struct_new_impl_msvc_guest ENDP
EXTERN gc_struct_set_impl_msvc_target:QWORD
PUBLIC gc_struct_set_impl_msvc_guest
gc_struct_set_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_struct_set_impl_msvc_target]
    add rsp, 40
    ret
gc_struct_set_impl_msvc_guest ENDP
EXTERN gc_struct_set_v128_impl_msvc_target:QWORD
PUBLIC gc_struct_set_v128_impl_msvc_guest
gc_struct_set_v128_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_struct_set_v128_impl_msvc_target]
    add rsp, 40
    ret
gc_struct_set_v128_impl_msvc_guest ENDP
EXTERN gc_type_check_subtype_impl_msvc_target:QWORD
PUBLIC gc_type_check_subtype_impl_msvc_guest
gc_type_check_subtype_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [gc_type_check_subtype_impl_msvc_target]
    add rsp, 40
    ret
gc_type_check_subtype_impl_msvc_guest ENDP
EXTERN memory_copy_indexed_internal_msvc_target:QWORD
PUBLIC memory_copy_indexed_internal_msvc_guest
memory_copy_indexed_internal_msvc_guest PROC
    sub rsp, 56
    mov QWORD PTR [rsp+32], r8
    mov QWORD PTR [rsp+40], r9
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [memory_copy_indexed_internal_msvc_target]
    add rsp, 56
    ret
memory_copy_indexed_internal_msvc_guest ENDP
EXTERN memory_fill_indexed_internal_msvc_target:QWORD
PUBLIC memory_fill_indexed_internal_msvc_guest
memory_fill_indexed_internal_msvc_guest PROC
    sub rsp, 40
    mov QWORD PTR [rsp+32], r8
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [memory_fill_indexed_internal_msvc_target]
    add rsp, 40
    ret
memory_fill_indexed_internal_msvc_guest ENDP
EXTERN memory_grow_indexed_internal_msvc_target:QWORD
PUBLIC memory_grow_indexed_internal_msvc_guest
memory_grow_indexed_internal_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [memory_grow_indexed_internal_msvc_target]
    add rsp, 40
    ret
memory_grow_indexed_internal_msvc_guest ENDP
EXTERN memory_init_impl_msvc_target:QWORD
PUBLIC memory_init_impl_msvc_guest
memory_init_impl_msvc_guest PROC
    sub rsp, 56
    mov QWORD PTR [rsp+32], r8
    mov QWORD PTR [rsp+40], r9
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [memory_init_impl_msvc_target]
    add rsp, 56
    ret
memory_init_impl_msvc_guest ENDP
EXTERN memory_size_indexed_internal_msvc_target:QWORD
PUBLIC memory_size_indexed_internal_msvc_guest
memory_size_indexed_internal_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [memory_size_indexed_internal_msvc_target]
    add rsp, 40
    ret
memory_size_indexed_internal_msvc_guest ENDP
EXTERN spectest_print_char_impl_msvc_target:QWORD
PUBLIC spectest_print_char_impl_msvc_guest
spectest_print_char_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [spectest_print_char_impl_msvc_target]
    add rsp, 40
    ret
spectest_print_char_impl_msvc_guest ENDP
EXTERN spectest_print_f32_impl_msvc_target:QWORD
PUBLIC spectest_print_f32_impl_msvc_guest
spectest_print_f32_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [spectest_print_f32_impl_msvc_target]
    add rsp, 40
    ret
spectest_print_f32_impl_msvc_guest ENDP
EXTERN spectest_print_f64_f64_impl_msvc_target:QWORD
PUBLIC spectest_print_f64_f64_impl_msvc_guest
spectest_print_f64_f64_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [spectest_print_f64_f64_impl_msvc_target]
    add rsp, 40
    ret
spectest_print_f64_f64_impl_msvc_guest ENDP
EXTERN spectest_print_f64_impl_msvc_target:QWORD
PUBLIC spectest_print_f64_impl_msvc_guest
spectest_print_f64_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [spectest_print_f64_impl_msvc_target]
    add rsp, 40
    ret
spectest_print_f64_impl_msvc_guest ENDP
EXTERN spectest_print_i32_f32_impl_msvc_target:QWORD
PUBLIC spectest_print_i32_f32_impl_msvc_guest
spectest_print_i32_f32_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [spectest_print_i32_f32_impl_msvc_target]
    add rsp, 40
    ret
spectest_print_i32_f32_impl_msvc_guest ENDP
EXTERN spectest_print_i32_impl_msvc_target:QWORD
PUBLIC spectest_print_i32_impl_msvc_guest
spectest_print_i32_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [spectest_print_i32_impl_msvc_target]
    add rsp, 40
    ret
spectest_print_i32_impl_msvc_guest ENDP
EXTERN spectest_print_i64_impl_msvc_target:QWORD
PUBLIC spectest_print_i64_impl_msvc_guest
spectest_print_i64_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [spectest_print_i64_impl_msvc_target]
    add rsp, 40
    ret
spectest_print_i64_impl_msvc_guest ENDP
EXTERN spectest_print_impl_msvc_target:QWORD
PUBLIC spectest_print_impl_msvc_guest
spectest_print_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [spectest_print_impl_msvc_target]
    add rsp, 40
    ret
spectest_print_impl_msvc_guest ENDP
EXTERN table_copy_impl_msvc_target:QWORD
PUBLIC table_copy_impl_msvc_guest
table_copy_impl_msvc_guest PROC
    sub rsp, 56
    mov QWORD PTR [rsp+32], r8
    mov QWORD PTR [rsp+40], r9
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [table_copy_impl_msvc_target]
    add rsp, 56
    ret
table_copy_impl_msvc_guest ENDP
EXTERN table_fill_impl_msvc_target:QWORD
PUBLIC table_fill_impl_msvc_guest
table_fill_impl_msvc_guest PROC
    sub rsp, 40
    mov QWORD PTR [rsp+32], r8
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [table_fill_impl_msvc_target]
    add rsp, 40
    ret
table_fill_impl_msvc_guest ENDP
EXTERN table_init_impl_msvc_target:QWORD
PUBLIC table_init_impl_msvc_guest
table_init_impl_msvc_guest PROC
    sub rsp, 56
    mov QWORD PTR [rsp+32], r8
    mov QWORD PTR [rsp+40], r9
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [table_init_impl_msvc_target]
    add rsp, 56
    ret
table_init_impl_msvc_guest ENDP
EXTERN wasi_args_get_impl_msvc_target:QWORD
PUBLIC wasi_args_get_impl_msvc_guest
wasi_args_get_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_args_get_impl_msvc_target]
    add rsp, 40
    ret
wasi_args_get_impl_msvc_guest ENDP
EXTERN wasi_args_sizes_get_impl_msvc_target:QWORD
PUBLIC wasi_args_sizes_get_impl_msvc_guest
wasi_args_sizes_get_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_args_sizes_get_impl_msvc_target]
    add rsp, 40
    ret
wasi_args_sizes_get_impl_msvc_guest ENDP
EXTERN wasi_clock_res_get_impl_msvc_target:QWORD
PUBLIC wasi_clock_res_get_impl_msvc_guest
wasi_clock_res_get_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_clock_res_get_impl_msvc_target]
    add rsp, 40
    ret
wasi_clock_res_get_impl_msvc_guest ENDP
EXTERN wasi_clock_time_get_impl_msvc_target:QWORD
PUBLIC wasi_clock_time_get_impl_msvc_guest
wasi_clock_time_get_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_clock_time_get_impl_msvc_target]
    add rsp, 40
    ret
wasi_clock_time_get_impl_msvc_guest ENDP
EXTERN wasi_environ_get_impl_msvc_target:QWORD
PUBLIC wasi_environ_get_impl_msvc_guest
wasi_environ_get_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_environ_get_impl_msvc_target]
    add rsp, 40
    ret
wasi_environ_get_impl_msvc_guest ENDP
EXTERN wasi_environ_sizes_get_impl_msvc_target:QWORD
PUBLIC wasi_environ_sizes_get_impl_msvc_guest
wasi_environ_sizes_get_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_environ_sizes_get_impl_msvc_target]
    add rsp, 40
    ret
wasi_environ_sizes_get_impl_msvc_guest ENDP
EXTERN wasi_fd_advise_impl_msvc_target:QWORD
PUBLIC wasi_fd_advise_impl_msvc_guest
wasi_fd_advise_impl_msvc_guest PROC
    sub rsp, 40
    mov QWORD PTR [rsp+32], r8
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_fd_advise_impl_msvc_target]
    add rsp, 40
    ret
wasi_fd_advise_impl_msvc_guest ENDP
EXTERN wasi_fd_allocate_impl_msvc_target:QWORD
PUBLIC wasi_fd_allocate_impl_msvc_guest
wasi_fd_allocate_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_fd_allocate_impl_msvc_target]
    add rsp, 40
    ret
wasi_fd_allocate_impl_msvc_guest ENDP
EXTERN wasi_fd_close_impl_msvc_target:QWORD
PUBLIC wasi_fd_close_impl_msvc_guest
wasi_fd_close_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_fd_close_impl_msvc_target]
    add rsp, 40
    ret
wasi_fd_close_impl_msvc_guest ENDP
EXTERN wasi_fd_datasync_impl_msvc_target:QWORD
PUBLIC wasi_fd_datasync_impl_msvc_guest
wasi_fd_datasync_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_fd_datasync_impl_msvc_target]
    add rsp, 40
    ret
wasi_fd_datasync_impl_msvc_guest ENDP
EXTERN wasi_fd_fdstat_get_impl_msvc_target:QWORD
PUBLIC wasi_fd_fdstat_get_impl_msvc_guest
wasi_fd_fdstat_get_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_fd_fdstat_get_impl_msvc_target]
    add rsp, 40
    ret
wasi_fd_fdstat_get_impl_msvc_guest ENDP
EXTERN wasi_fd_fdstat_set_flags_impl_msvc_target:QWORD
PUBLIC wasi_fd_fdstat_set_flags_impl_msvc_guest
wasi_fd_fdstat_set_flags_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_fd_fdstat_set_flags_impl_msvc_target]
    add rsp, 40
    ret
wasi_fd_fdstat_set_flags_impl_msvc_guest ENDP
EXTERN wasi_fd_fdstat_set_rights_impl_msvc_target:QWORD
PUBLIC wasi_fd_fdstat_set_rights_impl_msvc_guest
wasi_fd_fdstat_set_rights_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_fd_fdstat_set_rights_impl_msvc_target]
    add rsp, 40
    ret
wasi_fd_fdstat_set_rights_impl_msvc_guest ENDP
EXTERN wasi_fd_filestat_get_impl_msvc_target:QWORD
PUBLIC wasi_fd_filestat_get_impl_msvc_guest
wasi_fd_filestat_get_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_fd_filestat_get_impl_msvc_target]
    add rsp, 40
    ret
wasi_fd_filestat_get_impl_msvc_guest ENDP
EXTERN wasi_fd_filestat_set_size_impl_msvc_target:QWORD
PUBLIC wasi_fd_filestat_set_size_impl_msvc_guest
wasi_fd_filestat_set_size_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_fd_filestat_set_size_impl_msvc_target]
    add rsp, 40
    ret
wasi_fd_filestat_set_size_impl_msvc_guest ENDP
EXTERN wasi_fd_filestat_set_times_impl_msvc_target:QWORD
PUBLIC wasi_fd_filestat_set_times_impl_msvc_guest
wasi_fd_filestat_set_times_impl_msvc_guest PROC
    sub rsp, 40
    mov QWORD PTR [rsp+32], r8
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_fd_filestat_set_times_impl_msvc_target]
    add rsp, 40
    ret
wasi_fd_filestat_set_times_impl_msvc_guest ENDP
EXTERN wasi_fd_pread_impl_msvc_target:QWORD
PUBLIC wasi_fd_pread_impl_msvc_guest
wasi_fd_pread_impl_msvc_guest PROC
    sub rsp, 56
    mov QWORD PTR [rsp+32], r8
    mov QWORD PTR [rsp+40], r9
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_fd_pread_impl_msvc_target]
    add rsp, 56
    ret
wasi_fd_pread_impl_msvc_guest ENDP
EXTERN wasi_fd_prestat_dir_name_impl_msvc_target:QWORD
PUBLIC wasi_fd_prestat_dir_name_impl_msvc_guest
wasi_fd_prestat_dir_name_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_fd_prestat_dir_name_impl_msvc_target]
    add rsp, 40
    ret
wasi_fd_prestat_dir_name_impl_msvc_guest ENDP
EXTERN wasi_fd_prestat_get_impl_msvc_target:QWORD
PUBLIC wasi_fd_prestat_get_impl_msvc_guest
wasi_fd_prestat_get_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_fd_prestat_get_impl_msvc_target]
    add rsp, 40
    ret
wasi_fd_prestat_get_impl_msvc_guest ENDP
EXTERN wasi_fd_pwrite_impl_msvc_target:QWORD
PUBLIC wasi_fd_pwrite_impl_msvc_guest
wasi_fd_pwrite_impl_msvc_guest PROC
    sub rsp, 56
    mov QWORD PTR [rsp+32], r8
    mov QWORD PTR [rsp+40], r9
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_fd_pwrite_impl_msvc_target]
    add rsp, 56
    ret
wasi_fd_pwrite_impl_msvc_guest ENDP
EXTERN wasi_fd_read_impl_msvc_target:QWORD
PUBLIC wasi_fd_read_impl_msvc_guest
wasi_fd_read_impl_msvc_guest PROC
    sub rsp, 40
    mov QWORD PTR [rsp+32], r8
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_fd_read_impl_msvc_target]
    add rsp, 40
    ret
wasi_fd_read_impl_msvc_guest ENDP
EXTERN wasi_fd_readdir_impl_msvc_target:QWORD
PUBLIC wasi_fd_readdir_impl_msvc_guest
wasi_fd_readdir_impl_msvc_guest PROC
    sub rsp, 56
    mov QWORD PTR [rsp+32], r8
    mov QWORD PTR [rsp+40], r9
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_fd_readdir_impl_msvc_target]
    add rsp, 56
    ret
wasi_fd_readdir_impl_msvc_guest ENDP
EXTERN wasi_fd_renumber_impl_msvc_target:QWORD
PUBLIC wasi_fd_renumber_impl_msvc_guest
wasi_fd_renumber_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_fd_renumber_impl_msvc_target]
    add rsp, 40
    ret
wasi_fd_renumber_impl_msvc_guest ENDP
EXTERN wasi_fd_seek_impl_msvc_target:QWORD
PUBLIC wasi_fd_seek_impl_msvc_guest
wasi_fd_seek_impl_msvc_guest PROC
    sub rsp, 40
    mov QWORD PTR [rsp+32], r8
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_fd_seek_impl_msvc_target]
    add rsp, 40
    ret
wasi_fd_seek_impl_msvc_guest ENDP
EXTERN wasi_fd_sync_impl_msvc_target:QWORD
PUBLIC wasi_fd_sync_impl_msvc_guest
wasi_fd_sync_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_fd_sync_impl_msvc_target]
    add rsp, 40
    ret
wasi_fd_sync_impl_msvc_guest ENDP
EXTERN wasi_fd_tell_impl_msvc_target:QWORD
PUBLIC wasi_fd_tell_impl_msvc_guest
wasi_fd_tell_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_fd_tell_impl_msvc_target]
    add rsp, 40
    ret
wasi_fd_tell_impl_msvc_guest ENDP
EXTERN wasi_fd_write_impl_msvc_target:QWORD
PUBLIC wasi_fd_write_impl_msvc_guest
wasi_fd_write_impl_msvc_guest PROC
    sub rsp, 40
    mov QWORD PTR [rsp+32], r8
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_fd_write_impl_msvc_target]
    add rsp, 40
    ret
wasi_fd_write_impl_msvc_guest ENDP
EXTERN wasi_path_create_directory_impl_msvc_target:QWORD
PUBLIC wasi_path_create_directory_impl_msvc_guest
wasi_path_create_directory_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_path_create_directory_impl_msvc_target]
    add rsp, 40
    ret
wasi_path_create_directory_impl_msvc_guest ENDP
EXTERN wasi_path_filestat_get_impl_msvc_target:QWORD
PUBLIC wasi_path_filestat_get_impl_msvc_guest
wasi_path_filestat_get_impl_msvc_guest PROC
    sub rsp, 56
    mov QWORD PTR [rsp+32], r8
    mov QWORD PTR [rsp+40], r9
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_path_filestat_get_impl_msvc_target]
    add rsp, 56
    ret
wasi_path_filestat_get_impl_msvc_guest ENDP
EXTERN wasi_path_filestat_set_times_impl_msvc_target:QWORD
PUBLIC wasi_path_filestat_set_times_impl_msvc_guest
wasi_path_filestat_set_times_impl_msvc_guest PROC
    sub rsp, 72
    mov QWORD PTR [rsp+32], r8
    mov QWORD PTR [rsp+40], r9
    mov rax, QWORD PTR [rsp+80]
    mov QWORD PTR [rsp+48], rax
    mov rax, QWORD PTR [rsp+88]
    mov QWORD PTR [rsp+56], rax
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_path_filestat_set_times_impl_msvc_target]
    add rsp, 72
    ret
wasi_path_filestat_set_times_impl_msvc_guest ENDP
EXTERN wasi_path_link_impl_msvc_target:QWORD
PUBLIC wasi_path_link_impl_msvc_guest
wasi_path_link_impl_msvc_guest PROC
    sub rsp, 72
    mov QWORD PTR [rsp+32], r8
    mov QWORD PTR [rsp+40], r9
    mov rax, QWORD PTR [rsp+80]
    mov QWORD PTR [rsp+48], rax
    mov rax, QWORD PTR [rsp+88]
    mov QWORD PTR [rsp+56], rax
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_path_link_impl_msvc_target]
    add rsp, 72
    ret
wasi_path_link_impl_msvc_guest ENDP
EXTERN wasi_path_open_impl_msvc_target:QWORD
PUBLIC wasi_path_open_impl_msvc_guest
wasi_path_open_impl_msvc_guest PROC
    sub rsp, 88
    mov QWORD PTR [rsp+32], r8
    mov QWORD PTR [rsp+40], r9
    mov rax, QWORD PTR [rsp+96]
    mov QWORD PTR [rsp+48], rax
    mov rax, QWORD PTR [rsp+104]
    mov QWORD PTR [rsp+56], rax
    mov rax, QWORD PTR [rsp+112]
    mov QWORD PTR [rsp+64], rax
    mov rax, QWORD PTR [rsp+120]
    mov QWORD PTR [rsp+72], rax
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_path_open_impl_msvc_target]
    add rsp, 88
    ret
wasi_path_open_impl_msvc_guest ENDP
EXTERN wasi_path_readlink_impl_msvc_target:QWORD
PUBLIC wasi_path_readlink_impl_msvc_guest
wasi_path_readlink_impl_msvc_guest PROC
    sub rsp, 56
    mov QWORD PTR [rsp+32], r8
    mov QWORD PTR [rsp+40], r9
    mov rax, QWORD PTR [rsp+64]
    mov QWORD PTR [rsp+48], rax
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_path_readlink_impl_msvc_target]
    add rsp, 56
    ret
wasi_path_readlink_impl_msvc_guest ENDP
EXTERN wasi_path_remove_directory_impl_msvc_target:QWORD
PUBLIC wasi_path_remove_directory_impl_msvc_guest
wasi_path_remove_directory_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_path_remove_directory_impl_msvc_target]
    add rsp, 40
    ret
wasi_path_remove_directory_impl_msvc_guest ENDP
EXTERN wasi_path_rename_impl_msvc_target:QWORD
PUBLIC wasi_path_rename_impl_msvc_guest
wasi_path_rename_impl_msvc_guest PROC
    sub rsp, 56
    mov QWORD PTR [rsp+32], r8
    mov QWORD PTR [rsp+40], r9
    mov rax, QWORD PTR [rsp+64]
    mov QWORD PTR [rsp+48], rax
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_path_rename_impl_msvc_target]
    add rsp, 56
    ret
wasi_path_rename_impl_msvc_guest ENDP
EXTERN wasi_path_symlink_impl_msvc_target:QWORD
PUBLIC wasi_path_symlink_impl_msvc_guest
wasi_path_symlink_impl_msvc_guest PROC
    sub rsp, 56
    mov QWORD PTR [rsp+32], r8
    mov QWORD PTR [rsp+40], r9
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_path_symlink_impl_msvc_target]
    add rsp, 56
    ret
wasi_path_symlink_impl_msvc_guest ENDP
EXTERN wasi_path_unlink_file_impl_msvc_target:QWORD
PUBLIC wasi_path_unlink_file_impl_msvc_guest
wasi_path_unlink_file_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_path_unlink_file_impl_msvc_target]
    add rsp, 40
    ret
wasi_path_unlink_file_impl_msvc_guest ENDP
EXTERN wasi_proc_exit_impl_msvc_target:QWORD
PUBLIC wasi_proc_exit_impl_msvc_guest
wasi_proc_exit_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_proc_exit_impl_msvc_target]
    add rsp, 40
    ret
wasi_proc_exit_impl_msvc_guest ENDP
EXTERN wasi_proc_raise_impl_msvc_target:QWORD
PUBLIC wasi_proc_raise_impl_msvc_guest
wasi_proc_raise_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_proc_raise_impl_msvc_target]
    add rsp, 40
    ret
wasi_proc_raise_impl_msvc_guest ENDP
EXTERN wasi_random_get_impl_msvc_target:QWORD
PUBLIC wasi_random_get_impl_msvc_guest
wasi_random_get_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_random_get_impl_msvc_target]
    add rsp, 40
    ret
wasi_random_get_impl_msvc_guest ENDP
EXTERN wasi_sched_yield_impl_msvc_target:QWORD
PUBLIC wasi_sched_yield_impl_msvc_guest
wasi_sched_yield_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_sched_yield_impl_msvc_target]
    add rsp, 40
    ret
wasi_sched_yield_impl_msvc_guest ENDP
EXTERN wasi_sock_accept_impl_msvc_target:QWORD
PUBLIC wasi_sock_accept_impl_msvc_guest
wasi_sock_accept_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_sock_accept_impl_msvc_target]
    add rsp, 40
    ret
wasi_sock_accept_impl_msvc_guest ENDP
EXTERN wasi_sock_recv_impl_msvc_target:QWORD
PUBLIC wasi_sock_recv_impl_msvc_guest
wasi_sock_recv_impl_msvc_guest PROC
    sub rsp, 56
    mov QWORD PTR [rsp+32], r8
    mov QWORD PTR [rsp+40], r9
    mov rax, QWORD PTR [rsp+64]
    mov QWORD PTR [rsp+48], rax
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_sock_recv_impl_msvc_target]
    add rsp, 56
    ret
wasi_sock_recv_impl_msvc_guest ENDP
EXTERN wasi_sock_send_impl_msvc_target:QWORD
PUBLIC wasi_sock_send_impl_msvc_guest
wasi_sock_send_impl_msvc_guest PROC
    sub rsp, 56
    mov QWORD PTR [rsp+32], r8
    mov QWORD PTR [rsp+40], r9
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_sock_send_impl_msvc_target]
    add rsp, 56
    ret
wasi_sock_send_impl_msvc_guest ENDP
EXTERN wasi_sock_shutdown_impl_msvc_target:QWORD
PUBLIC wasi_sock_shutdown_impl_msvc_guest
wasi_sock_shutdown_impl_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasi_sock_shutdown_impl_msvc_target]
    add rsp, 40
    ret
wasi_sock_shutdown_impl_msvc_guest ENDP
EXTERN wasmoon_jit_cancel_poll_msvc_target:QWORD
PUBLIC wasmoon_jit_cancel_poll_msvc_guest
wasmoon_jit_cancel_poll_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasmoon_jit_cancel_poll_msvc_target]
    add rsp, 40
    ret
wasmoon_jit_cancel_poll_msvc_guest ENDP
EXTERN wasmoon_jit_exception_delegate_msvc_target:QWORD
PUBLIC wasmoon_jit_exception_delegate_msvc_guest
wasmoon_jit_exception_delegate_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasmoon_jit_exception_delegate_msvc_target]
    add rsp, 40
    ret
wasmoon_jit_exception_delegate_msvc_guest ENDP
EXTERN wasmoon_jit_exception_get_spilled_local_msvc_target:QWORD
PUBLIC wasmoon_jit_exception_get_spilled_local_msvc_guest
wasmoon_jit_exception_get_spilled_local_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasmoon_jit_exception_get_spilled_local_msvc_target]
    add rsp, 40
    ret
wasmoon_jit_exception_get_spilled_local_msvc_guest ENDP
EXTERN wasmoon_jit_exception_get_tag_msvc_target:QWORD
PUBLIC wasmoon_jit_exception_get_tag_msvc_guest
wasmoon_jit_exception_get_tag_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasmoon_jit_exception_get_tag_msvc_target]
    add rsp, 40
    ret
wasmoon_jit_exception_get_tag_msvc_guest ENDP
EXTERN wasmoon_jit_exception_get_value_msvc_target:QWORD
PUBLIC wasmoon_jit_exception_get_value_msvc_guest
wasmoon_jit_exception_get_value_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasmoon_jit_exception_get_value_msvc_target]
    add rsp, 40
    ret
wasmoon_jit_exception_get_value_msvc_guest ENDP
EXTERN wasmoon_jit_exception_get_value_count_msvc_target:QWORD
PUBLIC wasmoon_jit_exception_get_value_count_msvc_guest
wasmoon_jit_exception_get_value_count_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasmoon_jit_exception_get_value_count_msvc_target]
    add rsp, 40
    ret
wasmoon_jit_exception_get_value_count_msvc_guest ENDP
EXTERN wasmoon_jit_exception_spill_locals_msvc_target:QWORD
PUBLIC wasmoon_jit_exception_spill_locals_msvc_guest
wasmoon_jit_exception_spill_locals_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasmoon_jit_exception_spill_locals_msvc_target]
    add rsp, 40
    ret
wasmoon_jit_exception_spill_locals_msvc_guest ENDP
EXTERN wasmoon_jit_exception_throw_msvc_target:QWORD
PUBLIC wasmoon_jit_exception_throw_msvc_guest
wasmoon_jit_exception_throw_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasmoon_jit_exception_throw_msvc_target]
    add rsp, 40
    ret
wasmoon_jit_exception_throw_msvc_guest ENDP
EXTERN wasmoon_jit_exception_throw_ref_msvc_target:QWORD
PUBLIC wasmoon_jit_exception_throw_ref_msvc_guest
wasmoon_jit_exception_throw_ref_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasmoon_jit_exception_throw_ref_msvc_target]
    add rsp, 40
    ret
wasmoon_jit_exception_throw_ref_msvc_guest ENDP
EXTERN wasmoon_jit_exception_throw_tag_msvc_target:QWORD
PUBLIC wasmoon_jit_exception_throw_tag_msvc_guest
wasmoon_jit_exception_throw_tag_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasmoon_jit_exception_throw_tag_msvc_target]
    add rsp, 40
    ret
wasmoon_jit_exception_throw_tag_msvc_guest ENDP
EXTERN wasmoon_jit_exception_try_begin_msvc_target:QWORD
PUBLIC wasmoon_jit_exception_try_begin_msvc_guest
wasmoon_jit_exception_try_begin_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasmoon_jit_exception_try_begin_msvc_target]
    add rsp, 40
    ret
wasmoon_jit_exception_try_begin_msvc_guest ENDP
EXTERN wasmoon_jit_exception_try_end_msvc_target:QWORD
PUBLIC wasmoon_jit_exception_try_end_msvc_guest
wasmoon_jit_exception_try_end_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasmoon_jit_exception_try_end_msvc_target]
    add rsp, 40
    ret
wasmoon_jit_exception_try_end_msvc_guest ENDP
EXTERN wasmoon_jit_gc_pop_root_scope_or_trap_msvc_target:QWORD
PUBLIC wasmoon_jit_gc_pop_root_scope_or_trap_msvc_guest
wasmoon_jit_gc_pop_root_scope_or_trap_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasmoon_jit_gc_pop_root_scope_or_trap_msvc_target]
    add rsp, 40
    ret
wasmoon_jit_gc_pop_root_scope_or_trap_msvc_guest ENDP
EXTERN wasmoon_jit_gc_push_root_scope_or_trap_msvc_target:QWORD
PUBLIC wasmoon_jit_gc_push_root_scope_or_trap_msvc_guest
wasmoon_jit_gc_push_root_scope_or_trap_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasmoon_jit_gc_push_root_scope_or_trap_msvc_target]
    add rsp, 40
    ret
wasmoon_jit_gc_push_root_scope_or_trap_msvc_guest ENDP
EXTERN wasmoon_jit_hostcall_msvc_target:QWORD
PUBLIC wasmoon_jit_hostcall_msvc_guest
wasmoon_jit_hostcall_msvc_guest PROC
    sub rsp, 40
    mov QWORD PTR [rsp+32], r8
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasmoon_jit_hostcall_msvc_target]
    add rsp, 40
    ret
wasmoon_jit_hostcall_msvc_guest ENDP
EXTERN wasmoon_jit_i32_sdiv_msvc_target:QWORD
PUBLIC wasmoon_jit_i32_sdiv_msvc_guest
wasmoon_jit_i32_sdiv_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasmoon_jit_i32_sdiv_msvc_target]
    add rsp, 40
    ret
wasmoon_jit_i32_sdiv_msvc_guest ENDP
EXTERN wasmoon_jit_i32_srem_msvc_target:QWORD
PUBLIC wasmoon_jit_i32_srem_msvc_guest
wasmoon_jit_i32_srem_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasmoon_jit_i32_srem_msvc_target]
    add rsp, 40
    ret
wasmoon_jit_i32_srem_msvc_guest ENDP
EXTERN wasmoon_jit_i32_udiv_msvc_target:QWORD
PUBLIC wasmoon_jit_i32_udiv_msvc_guest
wasmoon_jit_i32_udiv_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasmoon_jit_i32_udiv_msvc_target]
    add rsp, 40
    ret
wasmoon_jit_i32_udiv_msvc_guest ENDP
EXTERN wasmoon_jit_i32_urem_msvc_target:QWORD
PUBLIC wasmoon_jit_i32_urem_msvc_guest
wasmoon_jit_i32_urem_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasmoon_jit_i32_urem_msvc_target]
    add rsp, 40
    ret
wasmoon_jit_i32_urem_msvc_guest ENDP
EXTERN wasmoon_jit_i64_sdiv_msvc_target:QWORD
PUBLIC wasmoon_jit_i64_sdiv_msvc_guest
wasmoon_jit_i64_sdiv_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasmoon_jit_i64_sdiv_msvc_target]
    add rsp, 40
    ret
wasmoon_jit_i64_sdiv_msvc_guest ENDP
EXTERN wasmoon_jit_i64_srem_msvc_target:QWORD
PUBLIC wasmoon_jit_i64_srem_msvc_guest
wasmoon_jit_i64_srem_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasmoon_jit_i64_srem_msvc_target]
    add rsp, 40
    ret
wasmoon_jit_i64_srem_msvc_guest ENDP
EXTERN wasmoon_jit_i64_udiv_msvc_target:QWORD
PUBLIC wasmoon_jit_i64_udiv_msvc_guest
wasmoon_jit_i64_udiv_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasmoon_jit_i64_udiv_msvc_target]
    add rsp, 40
    ret
wasmoon_jit_i64_udiv_msvc_guest ENDP
EXTERN wasmoon_jit_i64_urem_msvc_target:QWORD
PUBLIC wasmoon_jit_i64_urem_msvc_guest
wasmoon_jit_i64_urem_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasmoon_jit_i64_urem_msvc_target]
    add rsp, 40
    ret
wasmoon_jit_i64_urem_msvc_guest ENDP
EXTERN wasmoon_jit_table_grow_msvc_target:QWORD
PUBLIC wasmoon_jit_table_grow_msvc_guest
wasmoon_jit_table_grow_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [wasmoon_jit_table_grow_msvc_target]
    add rsp, 40
    ret
wasmoon_jit_table_grow_msvc_guest ENDP
END
