#!/usr/bin/env python3

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path


CONSTRUCTOR_RE = re.compile(r"[A-Z][A-Za-z0-9]*\Z")
WIRE_NAME_RE = re.compile(r"[a-z][a-z0-9_]*\Z")
KIND_TO_TYPE = {"int": "Int", "bool": "Bool"}
KIND_TO_MOONBIT = {"int": "IntegerImmediate", "bool": "BooleanImmediate"}


@dataclass(frozen=True)
class Opcode:
    constructor: str
    wire_name: str
    kinds: tuple[str, ...]


def fail(path: Path, line_number: int, message: str) -> None:
    raise ValueError(f"{path}:{line_number}: {message}")


def parse_schema(path: Path) -> list[Opcode]:
    opcodes: list[Opcode] = []
    constructors: set[str] = set()
    wire_names: set[str] = set()
    for line_number, raw_line in enumerate(path.read_text().splitlines(), 1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        fields = line.split("|")
        if len(fields) != 3:
            fail(path, line_number, "expected constructor|wire name|immediate kinds")
        constructor, wire_name, encoded_kinds = fields
        if not CONSTRUCTOR_RE.fullmatch(constructor):
            fail(path, line_number, f"invalid constructor {constructor!r}")
        if constructor in constructors:
            fail(path, line_number, f"duplicate constructor {constructor!r}")
        if not WIRE_NAME_RE.fullmatch(wire_name):
            fail(path, line_number, f"invalid wire name {wire_name!r}")
        if wire_name in wire_names:
            fail(path, line_number, f"duplicate wire name {wire_name!r}")
        kinds = () if encoded_kinds == "-" else tuple(encoded_kinds.split(","))
        for kind in kinds:
            if kind not in KIND_TO_TYPE:
                fail(path, line_number, f"invalid immediate kind {kind!r}")
        constructors.add(constructor)
        wire_names.add(wire_name)
        opcodes.append(Opcode(constructor, wire_name, kinds))
    if not opcodes:
        raise ValueError(f"{path}: schema contains no opcodes")
    return opcodes


def enum_variant(opcode: Opcode) -> str:
    if not opcode.kinds:
        return f"  {opcode.constructor}"
    fields = ", ".join(KIND_TO_TYPE[kind] for kind in opcode.kinds)
    return f"  {opcode.constructor}({fields})"


def immediate_kinds(opcode: Opcode) -> str:
    values = ", ".join(KIND_TO_MOONBIT[kind] for kind in opcode.kinds)
    return f"[{values}]"


def payload_arm(opcode: Opcode, opcode_id: int) -> str:
    if not opcode.kinds:
        return f"    {opcode.constructor} => ({opcode_id}, imm([]))"
    variables = [f"imm{i}" for i in range(len(opcode.kinds))]
    pattern = f"{opcode.constructor}({', '.join(variables)})"
    encoded = [
        f"bool_imm({variable})" if kind == "bool" else variable
        for variable, kind in zip(variables, opcode.kinds, strict=True)
    ]
    return f"    {pattern} => ({opcode_id}, imm([{', '.join(encoded)}]))"


def decode_arm(opcode: Opcode, opcode_id: int) -> str:
    if not opcode.kinds:
        return f"    {opcode_id} => Some({opcode.constructor})"
    decoded = [
        f"imm_bool(imms[{index}])" if kind == "bool" else f"imms[{index}]"
        for index, kind in enumerate(opcode.kinds)
    ]
    return f"    {opcode_id} => Some({opcode.constructor}({', '.join(decoded)}))"


def spec_entry(opcode: Opcode, opcode_id: int) -> list[str]:
    return [
        "  {",
        f"    id: {opcode_id},",
        f'    typed_constructor: "{opcode.constructor}",',
        f'    wire_name: "{opcode.wire_name}",',
        f"    immediate_kinds: {immediate_kinds(opcode)},",
        "  },",
    ]


def generate(opcodes: list[Opcode], schema_name: str) -> str:
    lines = [
        f"// Generated by tools/generate_wasm_opcodes.py from {schema_name}.",
        "// DO NOT EDIT. Update the schema and run a Moon development command.",
        "",
        "///|",
        "pub(all) enum WasmOpcode {",
        *(enum_variant(opcode) for opcode in opcodes),
        "} derive(Debug, Eq, Hash)",
        "",
        "///|",
        "let wasm_opcode_specs : Array[WasmOpcodeSpec] = [",
    ]
    for opcode_id, opcode in enumerate(opcodes):
        lines.extend(spec_entry(opcode, opcode_id))
    lines.extend([
        "]",
        "",
        "///|",
        "fn opcode_payload(opcode : WasmOpcode) -> (Int, FixedArray[Int]) {",
        "  match opcode {",
        *(payload_arm(opcode, opcode_id) for opcode_id, opcode in enumerate(opcodes)),
        "  }",
        "}",
        "",
        "///|",
        "fn opcode_from_payload(",
        "  id : Int,",
        "  imms : FixedArray[Int],",
        ") -> WasmOpcode? {",
        "  match id {",
        *(decode_arm(opcode, opcode_id) for opcode_id, opcode in enumerate(opcodes)),
        "    _ => None",
        "  }",
        "}",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        generated = generate(parse_schema(args.input), args.input.name)
    except (OSError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    if args.check:
        try:
            current = args.output.read_text()
        except OSError as error:
            print(f"error: {error}", file=sys.stderr)
            return 1
        if current != generated:
            print(f"error: {args.output} is stale", file=sys.stderr)
            return 1
        return 0
    if not args.output.exists() or args.output.read_text() != generated:
        args.output.write_text(generated)
        print(f"generated {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
