"""Generate MSVC bridges for the integer/pointer-only private guest helper ABI."""
from pathlib import Path
import argparse
import re

ROOT = Path(__file__).resolve().parents[2] / 'modules/wasmoon_jit/jit_ffi'


def generate(root=ROOT):
    functions = {}
    used = set()
    for path in root.glob('*.c'):
        source = path.read_text()
        used.update(re.findall(r'WASMOON_GUEST_ADDRESS\((\w+)\)', source))
        for match in re.finditer(r'([\w*]+)\s+WASMOON_GUEST_ABI\s+(\w+)\s*\(([^)]*)\)\s*\{', source):
            args = match[3].strip()
            if re.search(r'\b(float|double)\b|\.\.\.', args):
                raise ValueError(f'Unsupported guest helper signature: {match[2]}')
            functions[match[2]] = 0 if args in ('', 'void') else len(args.split(','))
    guard = 'WASMOON_' + root.name.upper() + '_MSVC_GUEST_BRIDGES_H'
    header = ['// Generated by scripts/msvc/generate_guest_bridges.py. Do not edit.',
              f'#ifndef {guard}', f'#define {guard}']
    asm = ['; Generated by scripts/msvc/generate_guest_bridges.py. Do not edit.', 'option casemap:none', '.code']
    for name in sorted(used):
        count = functions[name]
        header.append(f'extern void {name}_msvc_guest(void);')
        # Win64 shadow space and stack arguments, with 16-byte call alignment.
        stack = max(count - 4, 0) * 8 + 32
        stack += 8 if stack % 16 == 0 else 0
        asm += [f'EXTERN {name}_msvc_target:QWORD', f'PUBLIC {name}_msvc_guest',
                f'{name}_msvc_guest PROC', f'    sub rsp, {stack}']
        for i in range(4, count):
            if i < 6:
                src = ['r8', 'r9'][i - 4]
            else:
                asm.append(f'    mov rax, QWORD PTR [rsp+{stack + 8 + (i - 6) * 8}]')
                src = 'rax'
            asm.append(f'    mov QWORD PTR [rsp+{32 + (i - 4) * 8}], {src}')
        asm += ['    mov r10, rdx', '    mov r11, rcx', '    mov rcx, rdi',
                '    mov rdx, rsi', '    mov r8, r10', '    mov r9, r11',
                f'    call QWORD PTR [{name}_msvc_target]', f'    add rsp, {stack}',
                '    ret', f'{name}_msvc_guest ENDP']
    header += ['#endif', '']
    asm += ['END', '']
    return {'msvc_guest_bridges.h': '\n'.join(header), 'msvc_guest_bridges.asm': '\n'.join(asm)}


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for root in [ROOT, ROOT.parent / 'native_test_support']:
        for name, content in generate(root).items():
            path = root / name
            if args.check:
                if path.read_text() != content:
                    raise SystemExit(f'Stale generated file: {path}')
            else:
                path.write_text(content)
