#!/usr/bin/env python3
"""Generate WASI HTTP contracts from the pinned upstream WIT snapshot."""
import argparse
import importlib.util
import json
from pathlib import Path
import sys

sys.dont_write_bytecode = True
ROOT = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location(
    "contracts", ROOT.parent / "wasi_component/tools/generate_wasi_contracts.py"
)
contracts = importlib.util.module_from_spec(spec)
spec.loader.exec_module(contracts)
parser = argparse.ArgumentParser(__doc__)
parser.add_argument("--check", action="store_true")
parser.add_argument("--refresh-json", action="store_true")
parser.add_argument("--verify-wit", action="store_true")
args = parser.parse_args()
path = ROOT / "wit/contracts.json"
if args.refresh_json or args.verify_wit:
    resolved = contracts.load_resolution("wasm-tools", ROOT / "wit", "host")
    text = json.dumps(resolved, indent=2, ensure_ascii=False) + "\n"
    if args.verify_wit and path.read_text() != text:
        raise SystemExit("HTTP WIT resolution is stale")
    if args.refresh_json:
        path.write_text(text)
resolution = json.loads(path.read_text())
lines = ["// Generated by generate_contracts.py. DO NOT EDIT.", ""]
lines += contracts.emit_snapshot("http", resolution, contracts.snapshot_hash(ROOT / "wit"))
for interface in resolution["interfaces"]:
    if contracts.interface_name(resolution, interface) == "wasi:http@0.3.0/types":
        names = [contracts.moon_string(n) for n in interface["functions"]]
        lines += ["///|", "fn http_type_functions() -> Array[String] {", "  [" + ", ".join(names) + "]", "}", ""]
output = ROOT / "contracts_generated.mbt"
text = "\n".join(lines)
if args.check:
    if output.read_text() != text:
        raise SystemExit("HTTP generated contracts are stale")
else:
    output.write_text(text)
