;; Dropped segments are empty sources; zero lengths still require valid offsets.
(module
  (type $data (array (mut i32)))
  (type $refs (array (mut funcref)))
  (data $d "1234")
  (elem $e funcref (ref.null func))
  (func (export "drop") (data.drop $d) (elem.drop $e))
  (func (export "new-data") (param i32) (result i32)
    (array.len (array.new_data $data $d (local.get 0) (i32.const 0))))
  (func (export "new-elem") (param i32) (result i32)
    (array.len (array.new_elem $refs $e (local.get 0) (i32.const 0))))
  (func (export "init-data") (param i32 i32)
    (array.init_data $data $d (array.new_default $data (i32.const 0))
      (local.get 0) (local.get 1) (i32.const 0)))
  (func (export "init-elem") (param i32 i32)
    (array.init_elem $refs $e (array.new_default $refs (i32.const 0))
      (local.get 0) (local.get 1) (i32.const 0))))
(invoke "drop")
(assert_return (invoke "new-data" (i32.const 0)) (i32.const 0))
(assert_return (invoke "new-elem" (i32.const 0)) (i32.const 0))
(assert_trap (invoke "new-data" (i32.const 1)) "out of bounds memory access")
(assert_trap (invoke "new-elem" (i32.const 1)) "out of bounds table access")
(assert_return (invoke "init-data" (i32.const 0) (i32.const 0)))
(assert_return (invoke "init-elem" (i32.const 0) (i32.const 0)))
(assert_trap (invoke "init-data" (i32.const 1) (i32.const 0)) "out of bounds array access")
(assert_trap (invoke "init-elem" (i32.const 1) (i32.const 0)) "out of bounds array access")
(assert_trap (invoke "init-data" (i32.const 0) (i32.const 1)) "out of bounds memory access")
(assert_trap (invoke "init-elem" (i32.const 0) (i32.const 1)) "out of bounds table access")

;; Zero-length table initialization still checks both ranges after elem.drop.
(module
 (table 1 funcref)
 (elem $e func)
 (func (export "src") elem.drop $e i32.const 0 i32.const 1 i32.const 0 table.init $e)
 (func (export "dst") elem.drop $e i32.const 2 i32.const 0 i32.const 0 table.init $e))
(assert_trap (invoke "src") "out of bounds table access")
(assert_trap (invoke "dst") "out of bounds table access")

(module
 (table i64 1 funcref)
 (elem $e func)
 (func (export "dst64") (param i64)
  elem.drop $e local.get 0 i32.const 0 i32.const 0 table.init $e))
(assert_return (invoke "dst64" (i64.const 1)))
(assert_trap (invoke "dst64" (i64.const 0x100000000)) "out of bounds table access")
(assert_trap (invoke "dst64" (i64.const -1)) "out of bounds table access")
