(module
  (tag $e (param i32))
  (func $make (param i32) (result exnref)
    (block $caught (result exnref)
      (try_table (catch_all_ref $caught)
        (throw $e (local.get 0)))
      unreachable))
  (func (export "run") (result i32)
    (local $first exnref)
    (local.set $first (call $make (i32.const 11)))
    (drop (call $make (i32.const 22)))
    (block $caught (result i32)
      (try_table (catch $e $caught)
        (throw_ref (local.get $first)))
      unreachable)))
(assert_return (invoke "run") (i32.const 11))

(module
  (func (export "null") (throw_ref (ref.null exn))))
(assert_trap (invoke "null") "null reference")

(module $saved
  (tag $e (export "e") (param i32))
  (global $saved (export "saved") (mut exnref) (ref.null exn))
  (func (export "save")
    (global.set $saved
      (block $caught (result exnref)
        (try_table (catch_all_ref $caught) (throw $e (i32.const 37)))
        unreachable)))
  (func (export "replace")
    (block $caught (result exnref)
      (try_table (catch_all_ref $caught) (throw $e (i32.const 99)))
      unreachable)
    drop))
(register "saved" $saved)
(assert_return (invoke $saved "save"))
(assert_return (invoke $saved "replace"))
(module $other (tag (export "other") (param i32)))
(register "other" $other)
(module
  (import "other" "other" (tag $other (param i32)))
  (import "saved" "e" (tag $e (param i32)))
  (import "saved" "saved" (global $saved (mut exnref)))
  (func (export "rethrow") (result i32)
    (block $caught (result i32)
      (try_table (catch $e $caught) (throw_ref (global.get $saved)))
      unreachable)))
(assert_return (invoke "rethrow") (i32.const 37))

(module
  (tag $e (param v128))
  (func $make (param v128) (result exnref)
    (local $saved exnref)
    (block $caught (result v128 exnref)
      (try_table (catch_ref $e $caught)
        (throw $e (local.get 0)))
      unreachable)
    local.set $saved
    drop
    local.get $saved)
  (func (export "vector") (result v128)
    (local $saved exnref)
    (local.set $saved (call $make (v128.const i64x2 11 22)))
    (drop (call $make (v128.const i64x2 99 100)))
    (block $caught (result v128)
      (try_table (catch $e $caught) (throw_ref (local.get $saved)))
      unreachable)))
(assert_return (invoke "vector") (v128.const i64x2 11 22))
