;; Trap categories must survive interpreter execution, native lowering, and helpers.
(module
  (type $f (func))
  (type $a (array (mut i32)))
  (type $s (struct (field i32)))
  (memory 1 1 shared)
  (table 1 funcref)
  (func (export "memory") (drop (i32.load (i32.const 65536))))
  (func (export "table") (drop (table.get (i32.const 1))))
  (func (export "indirect-bounds") (call_indirect (type $f) (i32.const 1)))
  (func (export "indirect-null") (call_indirect (type $f) (i32.const 0)))
  (func (export "call-null") (call_ref $f (ref.null $f)))
  (func (export "ref-null") (drop (ref.as_non_null (ref.null any))))
  (func (export "cast") (drop (ref.cast (ref i31) (ref.null any))))
  (func (export "array-null") (drop (array.len (ref.null $a))))
  (func (export "struct-null") (drop (struct.get $s 0 (ref.null $s))))
  (func (export "array-bounds")
    (drop (array.get $a (array.new_default $a (i32.const 1)) (i32.const 1))))
  (func (export "atomic-alignment") (drop (i32.atomic.load (i32.const 1))))
  (func (export "nan") (drop (i32.trunc_f64_s (f64.const nan))))
  (func (export "overflow") (drop (i32.trunc_f64_s (f64.const 0x1p32))))
  (func (export "integer divide by zero") unreachable))
(assert_trap (invoke "memory") "out of bounds memory access")
(assert_trap (invoke "table") "out of bounds table access")
(assert_trap (invoke "indirect-bounds") "undefined element")
(assert_trap (invoke "indirect-null") "uninitialized element")
(assert_trap (invoke "call-null") "null function reference")
(assert_trap (invoke "ref-null") "null reference")
(assert_trap (invoke "cast") "cast failure")
(assert_trap (invoke "array-null") "null array reference")
(assert_trap (invoke "struct-null") "null structure reference")
(assert_trap (invoke "array-bounds") "out of bounds array access")
(assert_trap (invoke "atomic-alignment") "unaligned atomic")
(assert_trap (invoke "nan") "invalid conversion to integer")
(assert_trap (invoke "overflow") "integer overflow")
(assert_trap (invoke "integer divide by zero") "unreachable")
