;; Independent high-address canonical ABI controls. The low 32-bit alias remains zero.

(component
  (core module $m
    (memory (export "memory") 32770)
    (global $next (mut i32) (i32.const 2147549184))
    (func (export "realloc") (param i32 i32 i32 i32) (result i32)
      (local $ptr i32)
      (if (i32.ne (local.get 0) (i32.const 0))
        (then
          (global.set $next (i32.add (local.get 0) (local.get 3)))
          (return (local.get 0))))
      (local.set $ptr (i32.and (i32.add (global.get $next) (i32.const 7)) (i32.const -8)))
      (global.set $next (i32.add (local.get $ptr) (local.get 3)))
      (local.get $ptr))
    (func (export "roundtrip") (param i32 i32 i32 i32) (result i32)
      (i32.store (i32.const 2147581952) (local.get 0))
      (i32.store offset=4 (i32.const 2147581952) (local.get 1))
      (i32.store offset=8 (i32.const 2147581952) (local.get 2))
      (i32.store offset=12 (i32.const 2147581952) (local.get 3))
      (i32.const 2147581952)))
  (core instance $m (instantiate $m))
  (func (export "roundtrip") (param "value" (tuple string (list u32)))
    (result (tuple string (list u32)))
    (canon lift (core func $m "roundtrip") string-encoding=utf8
      (memory (core memory $m "memory")) (realloc (core func $m "realloc")))))
(assert_return (invoke "roundtrip" (tuple.const (str.const "AéΣ🙂") (list.const (u32.const 17) (u32.const 4294967295))))
  (tuple.const (str.const "AéΣ🙂") (list.const (u32.const 17) (u32.const 4294967295))))
(assert_return (invoke "roundtrip" (tuple.const (str.const "") (list.const)))
  (tuple.const (str.const "") (list.const)))

(component
  (core module $m
    (memory (export "memory") 32770)
    (global $next (mut i32) (i32.const 2147549184))
    (func (export "realloc") (param i32 i32 i32 i32) (result i32)
      (local $ptr i32)
      (if (i32.ne (local.get 0) (i32.const 0))
        (then
          (global.set $next (i32.add (local.get 0) (local.get 3)))
          (return (local.get 0))))
      (local.set $ptr (i32.and (i32.add (global.get $next) (i32.const 7)) (i32.const -8)))
      (global.set $next (i32.add (local.get $ptr) (local.get 3)))
      (local.get $ptr))
    (func (export "roundtrip") (param i32 i32 i32 i32) (result i32)
      (i32.store (i32.const 2147581952) (local.get 0))
      (i32.store offset=4 (i32.const 2147581952) (local.get 1))
      (i32.store offset=8 (i32.const 2147581952) (local.get 2))
      (i32.store offset=12 (i32.const 2147581952) (local.get 3))
      (i32.const 2147581952)))
  (core instance $m (instantiate $m))
  (func (export "roundtrip") (param "value" (tuple string (list u32)))
    (result (tuple string (list u32)))
    (canon lift (core func $m "roundtrip") string-encoding=utf16
      (memory (core memory $m "memory")) (realloc (core func $m "realloc")))))
(assert_return (invoke "roundtrip" (tuple.const (str.const "AéΣ🙂") (list.const (u32.const 17) (u32.const 4294967295))))
  (tuple.const (str.const "AéΣ🙂") (list.const (u32.const 17) (u32.const 4294967295))))
(assert_return (invoke "roundtrip" (tuple.const (str.const "") (list.const)))
  (tuple.const (str.const "") (list.const)))

(component
  (core module $m
    (memory (export "memory") 32770)
    (global $next (mut i32) (i32.const 2147549184))
    (func (export "realloc") (param i32 i32 i32 i32) (result i32)
      (local $ptr i32)
      (if (i32.ne (local.get 0) (i32.const 0))
        (then
          (global.set $next (i32.add (local.get 0) (local.get 3)))
          (return (local.get 0))))
      (local.set $ptr (i32.and (i32.add (global.get $next) (i32.const 7)) (i32.const -8)))
      (global.set $next (i32.add (local.get $ptr) (local.get 3)))
      (local.get $ptr))
    (func (export "roundtrip") (param i32 i32 i32 i32) (result i32)
      (i32.store (i32.const 2147581952) (local.get 0))
      (i32.store offset=4 (i32.const 2147581952) (local.get 1))
      (i32.store offset=8 (i32.const 2147581952) (local.get 2))
      (i32.store offset=12 (i32.const 2147581952) (local.get 3))
      (i32.const 2147581952)))
  (core instance $m (instantiate $m))
  (func (export "roundtrip") (param "value" (tuple string (list u32)))
    (result (tuple string (list u32)))
    (canon lift (core func $m "roundtrip") string-encoding=latin1+utf16
      (memory (core memory $m "memory")) (realloc (core func $m "realloc")))))
(assert_return (invoke "roundtrip" (tuple.const (str.const "AéΣ🙂") (list.const (u32.const 17) (u32.const 4294967295))))
  (tuple.const (str.const "AéΣ🙂") (list.const (u32.const 17) (u32.const 4294967295))))
(assert_return (invoke "roundtrip" (tuple.const (str.const "") (list.const)))
  (tuple.const (str.const "") (list.const)))

(component
  (component $Backend
  (core module $m
    (memory (export "memory") i64 65538)
    (global $next (mut i64) (i64.const 4295032832))
    (func (export "realloc") (param i64 i64 i64 i64) (result i64)
      (local $ptr i64)
      (if (i64.ne (local.get 0) (i64.const 0))
        (then
          (global.set $next (i64.add (local.get 0) (local.get 3)))
          (return (local.get 0))))
      (local.set $ptr (i64.and (i64.add (global.get $next) (i64.const 7)) (i64.const -8)))
      (global.set $next (i64.add (local.get $ptr) (local.get 3)))
      (local.get $ptr))
    (func (export "roundtrip") (param i64 i64 i64 i64) (result i64)
      (i64.store (i64.const 4295065600) (local.get 0))
      (i64.store offset=8 (i64.const 4295065600) (local.get 1))
      (i64.store offset=16 (i64.const 4295065600) (local.get 2))
      (i64.store offset=24 (i64.const 4295065600) (local.get 3))
      (i64.const 4295065600)))
  (core instance $m (instantiate $m))
  (func (export "roundtrip") (param "value" (tuple string (list u32)))
    (result (tuple string (list u32)))
    (canon lift (core func $m "roundtrip") string-encoding=utf8
      (memory (core memory $m "memory")) (realloc (core func $m "realloc")))))
  (instance $backend (instantiate $Backend))
  (component $Bridge
    (import "backend" (instance $b
      (export "roundtrip" (func (param "value" (tuple string (list u32)))
        (result (tuple string (list u32)))))))
    (core module $Libc
      (memory (export "memory") 1)
      (global $next (mut i32) (i32.const 1024))
      (func (export "realloc") (param i32 i32 i32 i32) (result i32)
        (local $p i32)
        (if (i32.ne (local.get 0) (i32.const 0))
          (then
            (global.set $next (i32.add (local.get 0) (local.get 3)))
            (return (local.get 0))))
        (local.set $p (i32.and (i32.add (global.get $next) (i32.const 7)) (i32.const -8)))
        (global.set $next (i32.add (local.get $p) (local.get 3)))
        (local.get $p)))
    (core instance $libc (instantiate $Libc))
    (core func $lower (canon lower (func $b "roundtrip")
      (memory (core memory $libc "memory")) (realloc (core func $libc "realloc"))))
    (core module $Run
      (import "" "call" (func $call (param i32 i32 i32 i32 i32)))
      (func (export "roundtrip") (param i32 i32 i32 i32) (result i32)
        (call $call (local.get 0) (local.get 1) (local.get 2) (local.get 3) (i32.const 64))
        (i32.const 64)))
    (core instance $run (instantiate $Run (with "" (instance (export "call" (func $lower))))))
    (func (export "roundtrip") (param "value" (tuple string (list u32)))
      (result (tuple string (list u32)))
      (canon lift (core func $run "roundtrip")
        (memory (core memory $libc "memory")) (realloc (core func $libc "realloc")))))
  (instance $bridge (instantiate $Bridge (with "backend" (instance $backend))))
  (export "roundtrip" (func $bridge "roundtrip")))
(assert_return (invoke "roundtrip" (tuple.const (str.const "AéΣ🙂") (list.const (u32.const 17) (u32.const 4294967295))))
  (tuple.const (str.const "AéΣ🙂") (list.const (u32.const 17) (u32.const 4294967295))))
(assert_return (invoke "roundtrip" (tuple.const (str.const "") (list.const)))
  (tuple.const (str.const "") (list.const)))

(component
  (component $Backend
  (core module $m
    (memory (export "memory") i64 65538)
    (global $next (mut i64) (i64.const 4295032832))
    (func (export "realloc") (param i64 i64 i64 i64) (result i64)
      (local $ptr i64)
      (if (i64.ne (local.get 0) (i64.const 0))
        (then
          (global.set $next (i64.add (local.get 0) (local.get 3)))
          (return (local.get 0))))
      (local.set $ptr (i64.and (i64.add (global.get $next) (i64.const 7)) (i64.const -8)))
      (global.set $next (i64.add (local.get $ptr) (local.get 3)))
      (local.get $ptr))
    (func (export "roundtrip") (param i64 i64 i64 i64) (result i64)
      (i64.store (i64.const 4295065600) (local.get 0))
      (i64.store offset=8 (i64.const 4295065600) (local.get 1))
      (i64.store offset=16 (i64.const 4295065600) (local.get 2))
      (i64.store offset=24 (i64.const 4295065600) (local.get 3))
      (i64.const 4295065600)))
  (core instance $m (instantiate $m))
  (func (export "roundtrip") (param "value" (tuple string (list u32)))
    (result (tuple string (list u32)))
    (canon lift (core func $m "roundtrip") string-encoding=utf16
      (memory (core memory $m "memory")) (realloc (core func $m "realloc")))))
  (instance $backend (instantiate $Backend))
  (component $Bridge
    (import "backend" (instance $b
      (export "roundtrip" (func (param "value" (tuple string (list u32)))
        (result (tuple string (list u32)))))))
    (core module $Libc
      (memory (export "memory") 1)
      (global $next (mut i32) (i32.const 1024))
      (func (export "realloc") (param i32 i32 i32 i32) (result i32)
        (local $p i32)
        (if (i32.ne (local.get 0) (i32.const 0))
          (then
            (global.set $next (i32.add (local.get 0) (local.get 3)))
            (return (local.get 0))))
        (local.set $p (i32.and (i32.add (global.get $next) (i32.const 7)) (i32.const -8)))
        (global.set $next (i32.add (local.get $p) (local.get 3)))
        (local.get $p)))
    (core instance $libc (instantiate $Libc))
    (core func $lower (canon lower (func $b "roundtrip")
      (memory (core memory $libc "memory")) (realloc (core func $libc "realloc"))))
    (core module $Run
      (import "" "call" (func $call (param i32 i32 i32 i32 i32)))
      (func (export "roundtrip") (param i32 i32 i32 i32) (result i32)
        (call $call (local.get 0) (local.get 1) (local.get 2) (local.get 3) (i32.const 64))
        (i32.const 64)))
    (core instance $run (instantiate $Run (with "" (instance (export "call" (func $lower))))))
    (func (export "roundtrip") (param "value" (tuple string (list u32)))
      (result (tuple string (list u32)))
      (canon lift (core func $run "roundtrip")
        (memory (core memory $libc "memory")) (realloc (core func $libc "realloc")))))
  (instance $bridge (instantiate $Bridge (with "backend" (instance $backend))))
  (export "roundtrip" (func $bridge "roundtrip")))
(assert_return (invoke "roundtrip" (tuple.const (str.const "AéΣ🙂") (list.const (u32.const 17) (u32.const 4294967295))))
  (tuple.const (str.const "AéΣ🙂") (list.const (u32.const 17) (u32.const 4294967295))))
(assert_return (invoke "roundtrip" (tuple.const (str.const "") (list.const)))
  (tuple.const (str.const "") (list.const)))

(component
  (component $Backend
  (core module $m
    (memory (export "memory") i64 65538)
    (global $next (mut i64) (i64.const 4295032832))
    (func (export "realloc") (param i64 i64 i64 i64) (result i64)
      (local $ptr i64)
      (if (i64.ne (local.get 0) (i64.const 0))
        (then
          (global.set $next (i64.add (local.get 0) (local.get 3)))
          (return (local.get 0))))
      (local.set $ptr (i64.and (i64.add (global.get $next) (i64.const 7)) (i64.const -8)))
      (global.set $next (i64.add (local.get $ptr) (local.get 3)))
      (local.get $ptr))
    (func (export "roundtrip") (param i64 i64 i64 i64) (result i64)
      (i64.store (i64.const 4295065600) (local.get 0))
      (i64.store offset=8 (i64.const 4295065600) (local.get 1))
      (i64.store offset=16 (i64.const 4295065600) (local.get 2))
      (i64.store offset=24 (i64.const 4295065600) (local.get 3))
      (i64.const 4295065600)))
  (core instance $m (instantiate $m))
  (func (export "roundtrip") (param "value" (tuple string (list u32)))
    (result (tuple string (list u32)))
    (canon lift (core func $m "roundtrip") string-encoding=latin1+utf16
      (memory (core memory $m "memory")) (realloc (core func $m "realloc")))))
  (instance $backend (instantiate $Backend))
  (component $Bridge
    (import "backend" (instance $b
      (export "roundtrip" (func (param "value" (tuple string (list u32)))
        (result (tuple string (list u32)))))))
    (core module $Libc
      (memory (export "memory") 1)
      (global $next (mut i32) (i32.const 1024))
      (func (export "realloc") (param i32 i32 i32 i32) (result i32)
        (local $p i32)
        (if (i32.ne (local.get 0) (i32.const 0))
          (then
            (global.set $next (i32.add (local.get 0) (local.get 3)))
            (return (local.get 0))))
        (local.set $p (i32.and (i32.add (global.get $next) (i32.const 7)) (i32.const -8)))
        (global.set $next (i32.add (local.get $p) (local.get 3)))
        (local.get $p)))
    (core instance $libc (instantiate $Libc))
    (core func $lower (canon lower (func $b "roundtrip")
      (memory (core memory $libc "memory")) (realloc (core func $libc "realloc"))))
    (core module $Run
      (import "" "call" (func $call (param i32 i32 i32 i32 i32)))
      (func (export "roundtrip") (param i32 i32 i32 i32) (result i32)
        (call $call (local.get 0) (local.get 1) (local.get 2) (local.get 3) (i32.const 64))
        (i32.const 64)))
    (core instance $run (instantiate $Run (with "" (instance (export "call" (func $lower))))))
    (func (export "roundtrip") (param "value" (tuple string (list u32)))
      (result (tuple string (list u32)))
      (canon lift (core func $run "roundtrip")
        (memory (core memory $libc "memory")) (realloc (core func $libc "realloc")))))
  (instance $bridge (instantiate $Bridge (with "backend" (instance $backend))))
  (export "roundtrip" (func $bridge "roundtrip")))
(assert_return (invoke "roundtrip" (tuple.const (str.const "AéΣ🙂") (list.const (u32.const 17) (u32.const 4294967295))))
  (tuple.const (str.const "AéΣ🙂") (list.const (u32.const 17) (u32.const 4294967295))))
(assert_return (invoke "roundtrip" (tuple.const (str.const "") (list.const)))
  (tuple.const (str.const "") (list.const)))
