;; early_return=True ready=False
(component
 (component $A
  (type $F (future))
  (core func $done (canon task.return))
  (core func $read (canon future.read $F))
  (core module $M
   (import "" "done" (func $done))
   (import "" "read" (func $read (param i32 i32) (result i32)))
   (global $resumed (mut i32) (i32.const 0))
   (func (export "first") (param i32) (result i32)
    call $done local.get 0 i32.const 0 call $read drop i32.const 1 global.set $resumed i32.const 0)
   (func (export "second") (result i32) global.get $resumed i32.eqz if unreachable end call $done i32.const 0)
   (func (export "cb") (param i32 i32 i32) (result i32) unreachable))
  (core instance $m (instantiate $M (with "" (instance (export "done" (func $done)) (export "read" (func $read))))))
  (func (export "first") async (param "f" $F) (canon lift (core func $m "first") async (callback (core func $m "cb"))))
  (func (export "second") async (canon lift (core func $m "second") async (callback (core func $m "cb")))))
 (component $B
  (type $F (future))
  (import "first" (func $first async (param "f" $F)))
  (import "second" (func $second async))
  (core func $new (canon future.new $F))
 (core func $write (canon future.write $F async))
  (core func $first (canon lower (func $first) async))
  (core func $second (canon lower (func $second) async))
  (core module $M
   (import "" "new" (func $new (result i64)))
 (import "" "write" (func $write (param i32 i32) (result i32)))
   (import "" "first" (func $first (param i32) (result i32)))
   (import "" "second" (func $second (result i32)))
   (func (export "run") (result i32) (local $p i64) call $new local.tee $p i32.wrap_i64 call $first drop call $second i32.const 15 i32.and))
  (core instance $m (instantiate $M (with "" (instance (export "new" (func $new)) (export "write" (func $write)) (export "first" (func $first)) (export "second" (func $second))))))
  (func (export "run") (result u32) (canon lift (core func $m "run"))))
 (instance $a (instantiate $A))
 (instance $b (instantiate $B (with "first" (func $a "first")) (with "second" (func $a "second"))))
 (export "run" (func $b "run")))

(assert_return (invoke "run") (u32.const 0))
;; early_return=True ready=True
(component
 (component $A
  (type $F (future))
  (core func $done (canon task.return))
  (core func $read (canon future.read $F))
  (core module $M
   (import "" "done" (func $done))
   (import "" "read" (func $read (param i32 i32) (result i32)))
   (global $resumed (mut i32) (i32.const 0))
   (func (export "first") (param i32) (result i32)
    call $done local.get 0 i32.const 0 call $read drop i32.const 1 global.set $resumed i32.const 0)
   (func (export "second") (result i32) global.get $resumed i32.eqz if unreachable end call $done i32.const 0)
   (func (export "cb") (param i32 i32 i32) (result i32) unreachable))
  (core instance $m (instantiate $M (with "" (instance (export "done" (func $done)) (export "read" (func $read))))))
  (func (export "first") async (param "f" $F) (canon lift (core func $m "first") async (callback (core func $m "cb"))))
  (func (export "second") async (canon lift (core func $m "second") async (callback (core func $m "cb")))))
 (component $B
  (type $F (future))
  (import "first" (func $first async (param "f" $F)))
  (import "second" (func $second async))
  (core func $new (canon future.new $F))
 (core func $write (canon future.write $F async))
  (core func $first (canon lower (func $first) async))
  (core func $second (canon lower (func $second) async))
  (core module $M
   (import "" "new" (func $new (result i64)))
 (import "" "write" (func $write (param i32 i32) (result i32)))
   (import "" "first" (func $first (param i32) (result i32)))
   (import "" "second" (func $second (result i32)))
   (func (export "run") (result i32) (local $p i64) call $new local.tee $p i32.wrap_i64 call $first drop local.get $p i64.const 32 i64.shr_u i32.wrap_i64 i32.const 0 call $write drop call $second i32.const 15 i32.and))
  (core instance $m (instantiate $M (with "" (instance (export "new" (func $new)) (export "write" (func $write)) (export "first" (func $first)) (export "second" (func $second))))))
  (func (export "run") (result u32) (canon lift (core func $m "run"))))
 (instance $a (instantiate $A))
 (instance $b (instantiate $B (with "first" (func $a "first")) (with "second" (func $a "second"))))
 (export "run" (func $b "run")))

(assert_return (invoke "run") (u32.const 0))
;; early_return=False ready=False
(component
 (component $A
  (type $F (future))
  (core func $done (canon task.return))
  (core func $read (canon future.read $F))
  (core module $M
   (import "" "done" (func $done))
   (import "" "read" (func $read (param i32 i32) (result i32)))
   (global $resumed (mut i32) (i32.const 0))
   (func (export "first") (param i32) (result i32)
    local.get 0 i32.const 0 call $read drop i32.const 1 global.set $resumed call $done i32.const 0)
   (func (export "second") (result i32) global.get $resumed i32.eqz if unreachable end call $done i32.const 0)
   (func (export "cb") (param i32 i32 i32) (result i32) unreachable))
  (core instance $m (instantiate $M (with "" (instance (export "done" (func $done)) (export "read" (func $read))))))
  (func (export "first") async (param "f" $F) (canon lift (core func $m "first") async (callback (core func $m "cb"))))
  (func (export "second") async (canon lift (core func $m "second") async (callback (core func $m "cb")))))
 (component $B
  (type $F (future))
  (import "first" (func $first async (param "f" $F)))
  (import "second" (func $second async))
  (core func $new (canon future.new $F))
 (core func $write (canon future.write $F async))
  (core func $first (canon lower (func $first) async))
  (core func $second (canon lower (func $second) async))
  (core module $M
   (import "" "new" (func $new (result i64)))
 (import "" "write" (func $write (param i32 i32) (result i32)))
   (import "" "first" (func $first (param i32) (result i32)))
   (import "" "second" (func $second (result i32)))
   (func (export "run") (result i32) (local $p i64) call $new local.tee $p i32.wrap_i64 call $first drop call $second i32.const 15 i32.and))
  (core instance $m (instantiate $M (with "" (instance (export "new" (func $new)) (export "write" (func $write)) (export "first" (func $first)) (export "second" (func $second))))))
  (func (export "run") (result u32) (canon lift (core func $m "run"))))
 (instance $a (instantiate $A))
 (instance $b (instantiate $B (with "first" (func $a "first")) (with "second" (func $a "second"))))
 (export "run" (func $b "run")))

(assert_return (invoke "run") (u32.const 0))
;; early_return=False ready=True
(component
 (component $A
  (type $F (future))
  (core func $done (canon task.return))
  (core func $read (canon future.read $F))
  (core module $M
   (import "" "done" (func $done))
   (import "" "read" (func $read (param i32 i32) (result i32)))
   (global $resumed (mut i32) (i32.const 0))
   (func (export "first") (param i32) (result i32)
    local.get 0 i32.const 0 call $read drop i32.const 1 global.set $resumed call $done i32.const 0)
   (func (export "second") (result i32) global.get $resumed i32.eqz if unreachable end call $done i32.const 0)
   (func (export "cb") (param i32 i32 i32) (result i32) unreachable))
  (core instance $m (instantiate $M (with "" (instance (export "done" (func $done)) (export "read" (func $read))))))
  (func (export "first") async (param "f" $F) (canon lift (core func $m "first") async (callback (core func $m "cb"))))
  (func (export "second") async (canon lift (core func $m "second") async (callback (core func $m "cb")))))
 (component $B
  (type $F (future))
  (import "first" (func $first async (param "f" $F)))
  (import "second" (func $second async))
  (core func $new (canon future.new $F))
 (core func $write (canon future.write $F async))
  (core func $first (canon lower (func $first) async))
  (core func $second (canon lower (func $second) async))
  (core module $M
   (import "" "new" (func $new (result i64)))
 (import "" "write" (func $write (param i32 i32) (result i32)))
   (import "" "first" (func $first (param i32) (result i32)))
   (import "" "second" (func $second (result i32)))
   (func (export "run") (result i32) (local $p i64) call $new local.tee $p i32.wrap_i64 call $first drop local.get $p i64.const 32 i64.shr_u i32.wrap_i64 i32.const 0 call $write drop call $second i32.const 15 i32.and))
  (core instance $m (instantiate $M (with "" (instance (export "new" (func $new)) (export "write" (func $write)) (export "first" (func $first)) (export "second" (func $second))))))
  (func (export "run") (result u32) (canon lift (core func $m "run"))))
 (instance $a (instantiate $A))
 (instance $b (instantiate $B (with "first" (func $a "first")) (with "second" (func $a "second"))))
 (export "run" (func $b "run")))

(assert_return (invoke "run") (u32.const 0))
