// Generated by scripts/msvc/generate_guest_bridges.py. Do not edit.
#ifndef WASMOON_NATIVE_TEST_SUPPORT_MSVC_GUEST_BRIDGES_H
#define WASMOON_NATIVE_TEST_SUPPORT_MSVC_GUEST_BRIDGES_H
extern void active_fiber_stack_probe_msvc_guest(void);
extern void fiber_stack_hostcall_probe_msvc_guest(void);
extern void hostcall_probe_trampoline_msvc_guest(void);
extern void mismatched_try_end_probe_msvc_guest(void);
extern void nested_activation_exception_probe_msvc_guest(void);
extern void nested_activation_gc_root_probe_msvc_guest(void);
extern void nested_hostcall_tls_probe_msvc_guest(void);
extern void nested_trap_probe_msvc_guest(void);
extern void parked_gc_root_probe_msvc_guest(void);
#endif
