; Generated by scripts/msvc/generate_guest_bridges.py. Do not edit.
option casemap:none
.code
EXTERN active_fiber_stack_probe_msvc_target:QWORD
PUBLIC active_fiber_stack_probe_msvc_guest
active_fiber_stack_probe_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [active_fiber_stack_probe_msvc_target]
    add rsp, 40
    ret
active_fiber_stack_probe_msvc_guest ENDP
EXTERN fiber_stack_hostcall_probe_msvc_target:QWORD
PUBLIC fiber_stack_hostcall_probe_msvc_guest
fiber_stack_hostcall_probe_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [fiber_stack_hostcall_probe_msvc_target]
    add rsp, 40
    ret
fiber_stack_hostcall_probe_msvc_guest ENDP
EXTERN hostcall_probe_trampoline_msvc_target:QWORD
PUBLIC hostcall_probe_trampoline_msvc_guest
hostcall_probe_trampoline_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [hostcall_probe_trampoline_msvc_target]
    add rsp, 40
    ret
hostcall_probe_trampoline_msvc_guest ENDP
EXTERN mismatched_try_end_probe_msvc_target:QWORD
PUBLIC mismatched_try_end_probe_msvc_guest
mismatched_try_end_probe_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [mismatched_try_end_probe_msvc_target]
    add rsp, 40
    ret
mismatched_try_end_probe_msvc_guest ENDP
EXTERN nested_activation_exception_probe_msvc_target:QWORD
PUBLIC nested_activation_exception_probe_msvc_guest
nested_activation_exception_probe_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [nested_activation_exception_probe_msvc_target]
    add rsp, 40
    ret
nested_activation_exception_probe_msvc_guest ENDP
EXTERN nested_activation_gc_root_probe_msvc_target:QWORD
PUBLIC nested_activation_gc_root_probe_msvc_guest
nested_activation_gc_root_probe_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [nested_activation_gc_root_probe_msvc_target]
    add rsp, 40
    ret
nested_activation_gc_root_probe_msvc_guest ENDP
EXTERN nested_hostcall_tls_probe_msvc_target:QWORD
PUBLIC nested_hostcall_tls_probe_msvc_guest
nested_hostcall_tls_probe_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [nested_hostcall_tls_probe_msvc_target]
    add rsp, 40
    ret
nested_hostcall_tls_probe_msvc_guest ENDP
EXTERN nested_trap_probe_msvc_target:QWORD
PUBLIC nested_trap_probe_msvc_guest
nested_trap_probe_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [nested_trap_probe_msvc_target]
    add rsp, 40
    ret
nested_trap_probe_msvc_guest ENDP
EXTERN parked_gc_root_probe_msvc_target:QWORD
PUBLIC parked_gc_root_probe_msvc_guest
parked_gc_root_probe_msvc_guest PROC
    sub rsp, 40
    mov r10, rdx
    mov r11, rcx
    mov rcx, rdi
    mov rdx, rsi
    mov r8, r10
    mov r9, r11
    call QWORD PTR [parked_gc_root_probe_msvc_target]
    add rsp, 40
    ret
parked_gc_root_probe_msvc_guest ENDP
END
