///|
pub extend Alias with Debug::{to_repr}

///|
pub extend Alias with Eq::{not_equal, equal}

///|
pub extend Alias with Show::{to_string, output}

///|
pub extend AliasTarget with Debug::{to_repr}

///|
pub extend AliasTarget with Eq::{not_equal, equal}

///|
pub extend BinaryKind with Debug::{to_repr}

///|
pub extend BinaryKind with Eq::{not_equal, equal}

///|
pub extend BinaryKind with Show::{to_string, output}

///|
pub extend Canon with Debug::{to_repr}

///|
pub extend Canon with Eq::{not_equal, equal}

///|
pub extend Canon with Show::{to_string, output}

///|
pub extend CanonOpt with Debug::{to_repr}

///|
pub extend CanonOpt with Eq::{not_equal, equal}

///|
pub extend Component with Debug::{to_repr}

///|
pub extend Component with Eq::{not_equal, equal}

///|
pub extend Component with Show::{to_string, output}

///|
pub extend ComponentBinary with Debug::{to_repr}

///|
pub extend ComponentBinary with Eq::{not_equal, equal}

///|
pub extend ComponentDecl with Debug::{to_repr}

///|
pub extend ComponentDecl with Eq::{not_equal, equal}

///|
pub extend ComponentParseError with Show::{output}

///|
pub extend CoreInlineExport with Debug::{to_repr}

///|
pub extend CoreInlineExport with Eq::{not_equal, equal}

///|
pub extend CoreInstanceDecl with Debug::{to_repr}

///|
pub extend CoreInstanceDecl with Eq::{not_equal, equal}

///|
pub extend CoreInstanceExpr with Debug::{to_repr}

///|
pub extend CoreInstanceExpr with Eq::{not_equal, equal}

///|
pub extend CoreInstantiateArg with Debug::{to_repr}

///|
pub extend CoreInstantiateArg with Eq::{not_equal, equal}

///|
pub extend Export with Debug::{to_repr}

///|
pub extend Export with Eq::{not_equal, equal}

///|
pub extend ExportName with Debug::{to_repr}

///|
pub extend ExportName with Eq::{not_equal, equal}

///|
pub extend ExternDesc with Debug::{to_repr}

///|
pub extend ExternDesc with Eq::{not_equal, equal}

///|
pub extend ExternDesc with Show::{to_string, output}

///|
pub extend FuncType with Debug::{to_repr}

///|
pub extend FuncType with Eq::{not_equal, equal}

///|
pub extend Import with Debug::{to_repr}

///|
pub extend Import with Eq::{not_equal, equal}

///|
pub extend ImportName with Debug::{to_repr}

///|
pub extend ImportName with Eq::{not_equal, equal}

///|
pub extend InlineExport with Debug::{to_repr}

///|
pub extend InlineExport with Eq::{not_equal, equal}

///|
pub extend Instance with Debug::{to_repr}

///|
pub extend Instance with Eq::{not_equal, equal}

///|
pub extend InstanceDecl with Debug::{to_repr}

///|
pub extend InstanceDecl with Eq::{not_equal, equal}

///|
pub extend InstanceExpr with Debug::{to_repr}

///|
pub extend InstanceExpr with Eq::{not_equal, equal}

///|
pub extend InstanceExpr with Show::{to_string, output}

///|
pub extend InstantiateArg with Debug::{to_repr}

///|
pub extend InstantiateArg with Eq::{not_equal, equal}

///|
pub extend NameAttribute with Debug::{to_repr}

///|
pub extend NameAttribute with Eq::{not_equal, equal}

///|
pub extend Param with Debug::{to_repr}

///|
pub extend Param with Eq::{not_equal, equal}

///|
pub extend PrimValType with Debug::{to_repr}

///|
pub extend PrimValType with Eq::{not_equal, equal}

///|
pub extend RecordField with Debug::{to_repr}

///|
pub extend RecordField with Eq::{not_equal, equal}

///|
pub extend ResourceKind with Debug::{to_repr}

///|
pub extend ResourceKind with Eq::{not_equal, equal}

///|
pub extend Section with Debug::{to_repr}

///|
pub extend Section with Eq::{not_equal, equal}

///|
pub extend Sort with Debug::{to_repr}

///|
pub extend Sort with Eq::{not_equal, equal}

///|
pub extend SortIdx with Debug::{to_repr}

///|
pub extend SortIdx with Eq::{not_equal, equal}

///|
pub extend SortIdx with Show::{to_string, output}

///|
pub extend Start with Debug::{to_repr}

///|
pub extend Start with Eq::{not_equal, equal}

///|
pub extend Start with Show::{to_string, output}

///|
pub extend StringEncoding with Debug::{to_repr}

///|
pub extend StringEncoding with Eq::{not_equal, equal}

///|
pub extend TypeBound with Debug::{to_repr}

///|
pub extend TypeBound with Eq::{not_equal, equal}

///|
pub extend TypeDef with Debug::{to_repr}

///|
pub extend TypeDef with Eq::{not_equal, equal}

///|
pub extend TypeDef with Show::{to_string, output}

///|
pub extend ValType with Debug::{to_repr}

///|
pub extend ValType with Eq::{not_equal, equal}

///|
pub extend ValueBound with Debug::{to_repr}

///|
pub extend ValueBound with Eq::{not_equal, equal}

///|
pub extend VariantCase with Debug::{to_repr}

///|
pub extend VariantCase with Eq::{not_equal, equal}
