///|
pub extend ArrayType with Debug::{to_repr}

///|
pub extend ArrayType with Eq::{not_equal, equal}

///|
pub extend BlockType with Debug::{to_repr}

///|
pub extend BlockType with Eq::{not_equal, equal}

///|
pub extend CatchHandler with Debug::{to_repr}

///|
pub extend CatchHandler with Eq::{not_equal, equal}

///|
pub extend CompositeType with Debug::{to_repr}

///|
pub extend CompositeType with Eq::{not_equal, equal}

///|
pub extend CompositeType with Show::{to_string, output}

///|
pub extend Data with Debug::{to_repr}

///|
pub extend Data with Eq::{not_equal, equal}

///|
pub extend ElemMode with Debug::{to_repr}

///|
pub extend ElemMode with Eq::{not_equal, equal}

///|
pub extend Element with Debug::{to_repr}

///|
pub extend Element with Eq::{not_equal, equal}

///|
pub extend Export with Debug::{to_repr}

///|
pub extend Export with Eq::{not_equal, equal}

///|
pub extend ExportDesc with Debug::{to_repr}

///|
pub extend ExportDesc with Eq::{not_equal, equal}

///|
pub extend FieldType with Debug::{to_repr}

///|
pub extend FieldType with Eq::{not_equal, equal}

///|
pub extend FuncType with Debug::{to_repr}

///|
pub extend FuncType with Eq::{not_equal, equal}

///|
pub extend FuncType with Show::{to_string, output}

///|
pub extend FunctionCode with Debug::{to_repr}

///|
pub extend FunctionCode with Eq::{not_equal, equal}

///|
pub extend FunctionCode with Show::{to_string, output}

///|
pub extend Global with Debug::{to_repr}

///|
pub extend Global with Eq::{not_equal, equal}

///|
pub extend GlobalType with Debug::{to_repr}

///|
pub extend GlobalType with Eq::{not_equal, equal}

///|
pub extend GlobalType with Show::{to_string, output}

///|
pub extend Import with Debug::{to_repr}

///|
pub extend Import with Eq::{not_equal, equal}

///|
pub extend ImportDesc with Debug::{to_repr}

///|
pub extend ImportDesc with Eq::{not_equal, equal}

///|
pub extend Instruction with Debug::{to_repr}

///|
pub extend Instruction with Eq::{not_equal, equal}

///|
pub extend Instruction with Show::{to_string, output}

///|
pub extend Limits with Debug::{to_repr}

///|
pub extend Limits with Eq::{not_equal, equal}

///|
pub extend MemoryType with Debug::{to_repr}

///|
pub extend MemoryType with Eq::{not_equal, equal}

///|
pub extend MemoryType with Show::{to_string, output}

///|
pub extend Module with Debug::{to_repr}

///|
pub extend Module with Show::{to_string, output}

///|
pub extend PackedType with Debug::{to_repr}

///|
pub extend PackedType with Eq::{not_equal, equal}

///|
pub extend StorageType with Debug::{to_repr}

///|
pub extend StorageType with Eq::{not_equal, equal}

///|
pub extend StorageType with Show::{to_string, output}

///|
pub extend StructType with Debug::{to_repr}

///|
pub extend StructType with Eq::{not_equal, equal}

///|
pub extend SubType with Debug::{to_repr}

///|
pub extend SubType with Eq::{not_equal, equal}

///|
pub extend SubType with Show::{to_string, output}

///|
pub extend Table with Debug::{to_repr}

///|
pub extend Table with Eq::{not_equal, equal}

///|
pub extend TableType with Debug::{to_repr}

///|
pub extend TableType with Eq::{not_equal, equal}

///|
pub extend TableType with Show::{to_string, output}

///|
pub extend TagType with Debug::{to_repr}

///|
pub extend TagType with Eq::{not_equal, equal}

///|
pub extend Value with Debug::{to_repr}

///|
pub extend Value with Eq::{not_equal, equal}

///|
pub extend Value with Show::{to_string, output}

///|
pub extend ValueType with Debug::{to_repr}

///|
pub extend ValueType with Eq::{not_equal, equal}

///|
pub extend ValueType with Show::{to_string, output}
