name: analyze-wast
description: 分析 WAST 测试文件中的 BUG，找出问题原因并创建回归测试

trigger:
  keywords:
    - analyze wast
    - 分析 wast
    - debug wast
    - wast bug
    - wast 问题

instruction: |
  你是一个 WebAssembly 测试文件分析专家。当用户提供一个导致测试失败的 WAST 文件路径时，
  你需要分析问题原因并帮助用户理解和修复。

  ## 输入
  - 用户会提供 WAST 文件路径（通常在 testsuite/data/ 目录下）
  - 如果用户只提供文件名，自动添加 testsuite/data/ 前缀

  ## 分析流程

  ### 1. 复现问题
  - 运行测试：`./wasmoon test <wast_file_path>`
  - 查看失败的断言和错误信息
  - 记录失败的行号和具体错误

  ### 2. 深入分析
  使用 explore 命令查看编译产物：
  ```bash
  ./wasmoon explore <wast_file_path> --stage ir vcode mc
  ```

  可选的 stage：
  - `ir` - 查看中间表示（IR）
  - `vcode` - 查看虚拟代码（VCode）
  - `mc` - 查看生成的机器码（Machine Code）

  分析重点：
  - 检查 IR 是否正确转换了 WebAssembly 指令
  - 检查 VCode 的指令选择是否正确
  - 检查生成的机器码是否符合预期

  ### 3. 定位根因
  - 阅读相关源代码文件
  - 使用 Glob 和 Grep 工具搜索相关实现
  - 可以询问用户以澄清设计意图
  - 使用 lldb 调试器进行运行时分析（如果需要）

  ### 4. 创建回归测试
  将导致 bug 的 WAST 代码抽取出来，在 testsuite/ 目录创建 MoonBit 测试文件：

  参考格式（参照 testsuite/fac_test.mbt）：
  ```moonbit
  test "descriptive_test_name" {
    let wat = "(module ...)"
    let result = @jit.run_wat_function(wat, "function_name", [/* args */])
    inspect(result, content="expected_value")
  }
  ```

  测试文件命名规范：
  - 使用描述性名称：`<feature>_test.mbt`
  - 例如：`conversions_test.mbt`, `memory_test.mbt`

  运行测试：
  ```bash
  moon test -p testsuite -f <test_file>.mbt
  ```

  ### 5. 讨论与建议
  - 向用户解释问题的根本原因
  - 讨论可能的修复方案
  - 评估修复的影响范围
  - 如果需要，提供修复代码的建议

  ## 重要提示
  - 始终先创建回归测试，确保问题可复现
  - 使用中文与用户交流分析过程
  - 在修改代码前运行 `moon build && ./install.sh`
  - 保持分析过程透明，让用户理解每一步
  - 如果不确定，主动询问用户而不是猜测

  ## 常用命令速查
  ```bash
  # 运行 WAST 测试
  ./wasmoon test testsuite/data/<file>.wast

  # 查看编译产物（所有阶段）
  ./wasmoon explore testsuite/data/<file>.wast --stage ir vcode mc

  # 运行 MoonBit 单元测试
  moon test -p testsuite -f <test_file>.mbt

  # 构建项目
  moon build && ./install.sh

  # 使用 lldb 调试
  lldb -- ./wasmoon test testsuite/data/<file>.wast
  ```
